#!/bin/bash
#
# ensure npm-shrinkwrap is committed with package.json changes

readonly staged=$(git diff --name-only --cached)

if [[ $staged == *"package.json"* && $staged != *"npm-shrinkwrap.json"* ]]; then
  node git-hooks/message.js shrinkwrap;
  exit 1;
fi
