#!/bin/sh
#
# Pre-push hooks

branch=$(git symbolic-ref --short HEAD)


function conditionallyGrunt {

    # check that remote branch exists
    git branch -r | if grep -q "origin/$branch"
    then

        # if remote branch exists, run grunt task if relevant
        git diff "origin/$branch" --cached --name-only | if grep $1
        then
            echo Running grunt $2 before pushing...
            echo
            grunt $2
        fi

    # if remote branch doesn't exist, run grunt task
    else
        echo Running grunt $2 before pushing to a new branch...
        echo
        grunt $2
    fi
}


# Validate CSS
CSS_SRC_PATTERN="\.scss"
conditionallyGrunt "$CSS_SRC_PATTERN" "validate:css validate:sass"
cssValidateResult=$?

# Validate JS
JS_SRC_PATTERN="\.js$"
conditionallyGrunt "$JS_SRC_PATTERN" "validate:js"
jsValidateResult=$?

# Test JS
conditionallyGrunt "[^/]\+/\(app\|test\)/assets/javascripts/.*$JS_SRC_PATTERN" "test:unit"
jsTestResult=$?


# Exit code 1 means don't commit and 0 means do commit
[ $cssValidateResult -ne 0 ] || [ $jsValidateResult -ne 0 ] || [ $jsTestResult -ne 0 ] && exit 1
exit 0
