package model.commercial.masterclasses

object Fixtures {

  val json = """{ "background_color" : "FFFFFF",
               |  "box_background_color" : "FFFFFF",
               |  "box_border_color" : "D5D5D3",
               |  "box_header_background_color" : "EFEFEF",
               |  "box_header_text_color" : "005580",
               |  "box_text_color" : "000000",
               |  "capacity" : 18,
               |  "category" : "seminars,conferences",
               |  "created" : "2013-02-15 09:50:35",
               |  "description" : {"html" : "<p>Everybody loves a good, juicy murder. So it's little wonder crime fiction is one of the UK's bestselling literary genres. Whether your tastes tend toward the gritty Jack Reacher procedural or the witty Father Brown whimsical, over the course of a weekend, acclaimed novelists William Ryan and M R Hall, joined by Literary Agent David Headley, will give an intensive and entertaining overview of the building blocks of crime fiction. And whether you're an absolute beginner or a much more experienced writer, this course will be of real value. From understanding the types of fiction agents, publishers and readers are looking for to giving practical and incisive help with your plotting and characterisation, through a series of lectures and workshops, you'll learn how to drive your novel forward without giving everything away - and while keeping your readers gripped. You'll leave the course with a step-by-step guide to developing your crime novel, and invaluable feedback from three professionals at the top of their game on how to continue.</p><P>A bunch of HTML goes here. <a href='http://www.theguardian.com/guardian-masterclasses/how-to-use-twitter-effectively-david-schneider-david-levin-social-media-course'>Full course and returns information on the Masterclasses website</a></P>"},
               |  "end_date" : "2013-04-21 17:00:00",
               |  "id" : "112342566",
               |  "link_color" : "EE6600",
               |  "locale" : "en",
               |  "logo" : "http://logologo.jpg",
               |  "logo_ssl" : "https://logologo.jpg",
               |  "modified" : "2013-04-26 03:23:31",
               |  "num_attendee_rows" : 18.0,
               |  "organizer" : { "description" : "",
               |      "id" : 3497465071,
               |      "long_description" : "",
               |      "name" : "",
               |      "url" : "http://www.eventbrite.com/org/3497465071"
               |    },
               |  "privacy" : "Public",
               |  "repeats" : "no",
               |  "start" : {"utc" : "2013-04-20T10:00:00z"},
               |  "status" : "live",
               |  "tags" : "travel, travel writing, masterclasses, short course, ",
               |  "text_color" : "005580",
               |  "ticket_classes" : [
               |          { "currency" : "GBP",
               |            "description" : "",
               |            "cost" : {"value" : 40000},
               |            "end_date" : "2013-04-20 09:30:00",
               |            "id" : 12319,
               |            "max" : 36,
               |            "min" : 1,
               |            "name" : "Travel writing weekend",
               |            "price" : "400.00",
               |            "start_date" : "2013-02-15 12:20:00",
               |            "type" : 0,
               |            "hidden" : false
               |          }
               |  ],
               |  "timezone" : "Europe/London",
               |  "timezone_offset" : "GMT+0100",
               |  "name" : {"text" : "Travel writing weekend"},
               |  "title_text_color" : "",
               |  "url" : "https://www.eventurl.com",
               |  "venue" : {
               |    "Lat-Long" : "51.534909 / -0.121693",
               |    "address" : {
               |      "address_1" : "Kings Place",
               |      "address_2" : "90 York Way",
               |      "city" : "London",
               |      "country" : "United Kingdom",
               |      "country_code" : "GB",
               |      "postal_code" : "N1 9GU",
               |      "region" : ""
               |    },
               |    "id" : 645187,
               |    "latitude" : 51.534908999999999,
               |    "longitude" : -0.121693,
               |    "name" : ""
               |  }
               |}""".stripMargin('|')


  val jsonWith2Tickets = """{ "background_color" : "FFFFFF",
                           |  "box_background_color" : "FFFFFF",
                           |  "box_border_color" : "D5D5D3",
                           |  "box_header_background_color" : "EFEFEF",
                           |  "box_header_text_color" : "005580",
                           |  "box_text_color" : "000000",
                           |  "capacity" : 18,
                           |  "category" : "seminars,conferences",
                           |  "created" : "2013-02-15 09:50:35",
                           |  "description" : {"html" : "<P>A bunch of HTML goes here. <a href='http://www.theguardian.com/guardian-masterclasses/how-to-use-twitter-effectively-david-schneider-david-levin-social-media-course'>Full course and returns information on the Masterclasses website</a></P>"},
                           |  "end_date" : "2013-04-21 17:00:00",
                           |  "id" : "112342566",
                           |  "link_color" : "EE6600",
                           |  "locale" : "en",
                           |  "logo" : "http://logologo.jpg",
                           |  "logo_ssl" : "https://logologo.jpg",
                           |  "modified" : "2013-04-26 03:23:31",
                           |  "num_attendee_rows" : 18.0,
                           |  "organizer" : { "description" : "",
                           |      "id" : 3497465071,
                           |      "long_description" : "",
                           |      "name" : "",
                           |      "url" : "http://www.eventbrite.com/org/3497465071"
                           |    },
                           |  "privacy" : "Public",
                           |  "repeats" : "no",
                           |  "start" : {"utc" : "2013-04-20T10:00:00z"},
                           |  "status" : "live",
                           |  "tags" : "travel, travel writing, masterclasses, short course, ",
                           |  "text_color" : "005580",
                           |  "ticket_classes" : [
                           |          { "currency" : "GBP",
                           |            "description" : "",
                           |            "cost" : {"value" : 40000},
                           |            "end_date" : "2013-04-20 09:30:00",
                           |            "id" : 12319,
                           |            "max" : 36,
                           |            "min" : 1,
                           |            "name" : "Travel writing weekend",
                           |            "price" : "400.00",
                           |            "start_date" : "2013-02-15 12:20:00",
                           |            "type" : 0,
                           |            "hidden" : false
                           |          },
                           |          { "currency" : "GBP",
                           |            "description" : "",
                           |            "cost" : {"value" : 260000},
                           |            "end_date" : "2013-04-20 09:30:00",
                           |            "id" : 12319,
                           |            "max" : 36,
                           |            "min" : 1,
                           |            "name" : "Travel writing weekend ticket b",
                           |            "price" : "400.00",
                           |            "start_date" : "2013-02-15 12:20:00",
                           |            "type" : 0,
                           |            "hidden" : false
                           |          } ],
                           |  "timezone" : "Europe/London",
                           |  "timezone_offset" : "GMT+0100",
                           |  "name" : {"text" : "Travel writing weekend"},
                           |  "title_text_color" : "",
                           |  "url" : "https://www.eventurl.com",
                           |  "venue" : { "Lat-Long" : "51.534909 / -0.121693",
                           |      "address" : "Kings Place",
                           |      "address_2" : "90 York Way",
                           |      "city" : "London",
                           |      "country" : "United Kingdom",
                           |      "country_code" : "GB",
                           |      "id" : 645187,
                           |      "latitude" : 51.534908999999999,
                           |      "longitude" : -0.121693,
                           |      "name" : "",
                           |      "postal_code" : "N1 9GU",
                           |      "region" : ""
                           |    }
                           |}""".stripMargin('|')

  val jsonWithNoLink = """{ "background_color" : "FFFFFF",
                         |  "box_background_color" : "FFFFFF",
                         |  "box_border_color" : "D5D5D3",
                         |  "box_header_background_color" : "EFEFEF",
                         |  "box_header_text_color" : "005580",
                         |  "box_text_color" : "000000",
                         |  "capacity" : 18,
                         |  "category" : "seminars,conferences",
                         |  "created" : "2013-02-15 09:50:35",
                         |  "description" : {"html" : "<P>A bunch of HTML goes here. <a href='http://www.theguardian.com/contactus'>Contact the Guardian</a></P>"},
                         |  "end_date" : "2013-04-21 17:00:00",
                         |  "id" : "112342566",
                         |  "link_color" : "EE6600",
                         |  "locale" : "en",
                         |  "logo" : "http://logologo.jpg",
                         |  "logo_ssl" : "https://logologo.jpg",
                         |  "modified" : "2013-04-26 03:23:31",
                         |  "num_attendee_rows" : 18.0,
                         |  "organizer" : { "description" : "",
                         |      "id" : 3497465071,
                         |      "long_description" : "",
                         |      "name" : "",
                         |      "url" : "http://www.eventbrite.com/org/3497465071"
                         |    },
                         |  "privacy" : "Public",
                         |  "repeats" : "no",
                         |  "start" : {"utc" : "2013-04-20T10:00:00z"},
                         |  "status" : "Live",
                         |  "tags" : "travel, travel writing, masterclasses, short course, ",
                         |  "text_color" : "005580",
                         |  "tickets" : [ { "ticket" : { "currency" : "GBP",
                         |            "description" : "",
                         |            "display_price" : "400.00",
                         |            "end_date" : "2013-04-20 09:30:00",
                         |            "id" : 12319,
                         |            "max" : 36,
                         |            "min" : 1,
                         |            "name" : "Travel writing weekend",
                         |            "price" : "400.00",
                         |            "start_date" : "2013-02-15 12:20:00",
                         |            "type" : 0,
                         |            "visible" : "true"
                         |          } } ],
                         |  "timezone" : "Europe/London",
                         |  "timezone_offset" : "GMT+0100",
                         |  "name" : {"text" : "Travel writing weekend"},
                         |  "title_text_color" : "",
                         |  "url" : "https://www.eventurl.com",
                         |  "venue" : { "Lat-Long" : "51.534909 / -0.121693",
                         |      "address" : "Kings Place",
                         |      "address_2" : "90 York Way",
                         |      "city" : "London",
                         |      "country" : "United Kingdom",
                         |      "country_code" : "GB",
                         |      "id" : 645187,
                         |      "latitude" : 51.534908999999999,
                         |      "longitude" : -0.121693,
                         |      "name" : "",
                         |      "postal_code" : "N1 9GU",
                         |      "region" : ""
                         |    }
                         |}""".stripMargin('|')

  val jsonWithInvisiblePrice = """{ "background_color" : "FFFFFF",
                                 |  "box_background_color" : "FFFFFF",
                                 |  "box_border_color" : "D5D5D3",
                                 |  "box_header_background_color" : "EFEFEF",
                                 |  "box_header_text_color" : "005580",
                                 |  "box_text_color" : "000000",
                                 |  "capacity" : 18,
                                 |  "category" : "seminars,conferences",
                                 |  "created" : "2013-02-15 09:50:35",
                                 |  "description" : {"html" : "<P>A bunch of HTML goes here. <a href='http://www.theguardian.com/guardian-masterclasses/how-to-use-twitter-effectively-david-schneider-david-levin-social-media-course'>Full course and returns information on the Masterclasses website</a></P>"},
                                 |  "end_date" : "2013-04-21 17:00:00",
                                 |  "id" : "112342566",
                                 |  "link_color" : "EE6600",
                                 |  "locale" : "en",
                                 |  "logo" : "http://logologo.jpg",
                                 |  "logo_ssl" : "https://logologo.jpg",
                                 |  "modified" : "2013-04-26 03:23:31",
                                 |  "num_attendee_rows" : 18.0,
                                 |  "organizer" : { "description" : "",
                                 |      "id" : 3497465071,
                                 |      "long_description" : "",
                                 |      "name" : "",
                                 |      "url" : "http://www.eventbrite.com/org/3497465071"
                                 |    },
                                 |  "privacy" : "Public",
                                 |  "repeats" : "no",
                                 |  "start" : {"utc" : "2013-04-20T10:00:00z"},
                                 |  "status" : "Live",
                                 |  "tags" : "travel, travel writing, masterclasses, short course, ",
                                 |  "text_color" : "005580",
                                 |  "ticket_classes" : [
                                 |          { "currency" : "GBP",
                                 |            "description" : "",
                                 |            "display_price" : "400.00",
                                 |            "end_date" : "2013-04-20 09:30:00",
                                 |            "id" : 12319,
                                 |            "max" : 36,
                                 |            "min" : 1,
                                 |            "name" : "Travel writing weekend",
                                 |            "cost" : {"value" : 40000},
                                 |            "start_date" : "2013-02-15 12:20:00",
                                 |            "type" : 0,
                                 |            "hidden" : false
                                 |          },
                                 |          { "currency" : "GBP",
                                 |            "description" : "",
                                 |            "display_price" : "2,600.00",
                                 |            "end_date" : "2013-04-20 09:30:00",
                                 |            "id" : 12319,
                                 |            "max" : 36,
                                 |            "min" : 1,
                                 |            "name" : "Travel writing weekend ticket b",
                                 |            "cost" : {"value" : 40000},
                                 |            "start_date" : "2013-02-15 12:20:00",
                                 |            "type" : 0,
                                 |            "hidden" : true
                                 |          } ],
                                 |  "timezone" : "Europe/London",
                                 |  "timezone_offset" : "GMT+0100",
                                 |  "name" : {"text" : "Travel writing weekend"},
                                 |  "title_text_color" : "",
                                 |  "url" : "https://www.eventurl.com",
                                 |  "venue" : { "Lat-Long" : "51.534909 / -0.121693",
                                 |      "address" : "Kings Place",
                                 |      "address_2" : "90 York Way",
                                 |      "city" : "London",
                                 |      "country" : "United Kingdom",
                                 |      "country_code" : "GB",
                                 |      "id" : 645187,
                                 |      "latitude" : 51.534908999999999,
                                 |      "longitude" : -0.121693,
                                 |      "name" : "",
                                 |      "postal_code" : "N1 9GU",
                                 |      "region" : ""
                                 |    }
                                 |}""".stripMargin
}
