package model.commercial.masterclasses

import org.scalatest.Matchers
import org.scalatest.FlatSpec
import play.api.libs.json._

class MasterClassFeedParsingTest extends FlatSpec with Matchers {
  val rawEventBriteFeed = """{ "events" : [ { "event" : { "background_color" : "FFFFFF",
                            |            "box_background_color" : "FFFFFF",
                            |            "box_border_color" : "D5D5D3",
                            |            "box_header_background_color" : "EFEFEF",
                            |            "box_header_text_color" : "005580",
                            |            "box_text_color" : "000000",
                            |            "capacity" : 18,
                            |            "category" : "seminars,conferences",
                            |            "created" : "2013-02-15 09:50:35",
                            |            "description" : "<p>Whole bunch of HTML goes here. <a href='http://www.theguardian.com/guardian-masterclasses/how-to-use-twitter-effectively-david-schneider-david-levin-social-media-course'>Link to Masterclass page in the Guardian</a></p>",
                            |            "end_date" : "2013-04-21 17:00:00",
                            |            "id" : 1323241,
                            |            "link_color" : "EE6600",
                            |            "locale" : "en",
                            |            "logo" : "logourl.jpg",
                            |            "logo_ssl" : "logourl.jpg",
                            |            "modified" : "2013-04-26 03:23:31",
                            |            "num_attendee_rows" : 18.0,
                            |            "organizer" : { "description" : "",
                            |                "id" : 3497465071,
                            |                "long_description" : "",
                            |                "name" : "",
                            |                "url" : "http://eventUrl.com"
                            |              },
                            |            "privacy" : "Public",
                            |            "repeats" : "no",
                            |            "start_date" : "2013-04-20 10:00:00",
                            |            "status" : "Completed",
                            |            "tags" : "travel, travel writing, masterclasses, short course, ",
                            |            "text_color" : "005580",
                            |            "tickets" : [ { "ticket" : { "currency" : "GBP",
                            |                      "description" : "",
                            |                      "display_price" : "400.00",
                            |                      "end_date" : "2013-04-20 09:30:00",
                            |                      "id" : 1,
                            |                      "max" : 36,
                            |                      "min" : 1,
                            |                      "name" : "Travel writing weekend",
                            |                      "price" : "400.00",
                            |                      "start_date" : "2013-02-15 12:20:00",
                            |                      "type" : 0,
                            |                      "visible" : "true"
                            |                    } } ],
                            |            "timezone" : "Europe/London",
                            |            "timezone_offset" : "GMT+0100",
                            |            "title" : "Travel writing weekend",
                            |            "title_text_color" : "",
                            |            "url" : "http://eventurl",
                            |            "venue" : { "Lat-Long" : "51.534909 / -0.121693",
                            |                "address" : "Kings Place",
                            |                "address_2" : "90 York Way",
                            |                "city" : "London",
                            |                "country" : "United Kingdom",
                            |                "country_code" : "GB",
                            |                "id" : 645187,
                            |                "latitude" : 51.534908999999999,
                            |                "longitude" : -0.121693,
                            |                "name" : "",
                            |                "postal_code" : "N1 9GU",
                            |                "region" : ""
                            |              }
                            |          } },
                            |      { "event" : { "background_color" : "FFFFFF",
                            |            "box_background_color" : "FFFFFF",
                            |            "box_border_color" : "D5D5D3",
                            |            "box_header_background_color" : "EFEFEF",
                            |            "box_header_text_color" : "005580",
                            |            "box_text_color" : "000000",
                            |            "capacity" : 0,
                            |            "category" : "",
                            |            "created" : "2013-04-18 02:27:38",
                            |            "description" : "<p><a href='http://www.theguardian.com/guardian-masterclasses/how-to-use-twitter-effectively-david-schneider-david-levin-social-media-course'>Link to Masterclass page in the Guardian</a></p>",
                            |            "end_date" : "2013-05-28 16:00:00",
                            |            "id" : 1231412,
                            |            "link_color" : "EE6600",
                            |            "locale" : "en_US",
                            |            "modified" : "2013-04-18 02:29:13",
                            |            "num_attendee_rows" : null,
                            |            "organizer" : { "description" : "",
                            |                "id" : 10,
                            |                "long_description" : "",
                            |                "name" : "",
                            |                "url" : "http://www.eventurl.com"
                            |              },
                            |            "privacy" : "Public",
                            |            "repeats" : "no",
                            |            "start_date" : "2013-05-28 13:00:00",
                            |            "status" : "Draft",
                            |            "tags" : "",
                            |            "text_color" : "005580",
                            |            "tickets" : [ { "ticket" : { "currency" : "GBP",
                            |                      "description" : "",
                            |                      "display_price" : "12.00",
                            |                      "end_date" : "2013-05-28 12:00:00",
                            |                      "id" : 21,
                            |                      "max" : 0,
                            |                      "min" : 0,
                            |                      "name" : "Ticket1",
                            |                      "price" : "12.00",
                            |                      "type" : 0,
                            |                      "visible" : "true"
                            |                    } },
                            |                { "ticket" : { "currency" : "GBP",
                            |                      "description" : "",
                            |                      "display_price" : "12.00",
                            |                      "end_date" : "2013-05-28 12:00:00",
                            |                      "id" : 213,
                            |                      "max" : 0,
                            |                      "min" : 0,
                            |                      "name" : "Ticket2",
                            |                      "price" : "12.00",
                            |                      "type" : 0,
                            |                      "visible" : "true"
                            |                    } }
                            |              ],
                            |            "timezone" : "Europe/London",
                            |            "timezone_offset" : "GMT+0100",
                            |            "title" : "",
                            |            "title_text_color" : "",
                            |            "url" : "https://www.eventurl.com"
                            |          } },
                            |      { "event" : { "background_color" : "FFFFFF",
                            |            "box_background_color" : "FFFFFF",
                            |            "box_border_color" : "D5D5D3",
                            |            "box_header_background_color" : "EFEFEF",
                            |            "box_header_text_color" : "005580",
                            |            "box_text_color" : "000000",
                            |            "capacity" : 15,
                            |            "category" : "seminars,conferences",
                            |            "created" : "2013-04-17 02:37:45",
                            |            "description" : "<P>More HTML GOES HERE.</P>",
                            |            "end_date" : "2013-06-09 17:00:00",
                            |            "id" : 23423523,
                            |            "link_color" : "EE6600",
                            |            "locale" : "en",
                            |            "logo" : "http://eventlogo.jpg",
                            |            "logo_ssl" : "http://eventlogl.jpg",
                            |            "modified" : "2013-06-14 03:26:37",
                            |            "num_attendee_rows" : 15.0,
                            |            "organizer" : { "description" : "",
                            |                "id" : 123142,
                            |                "long_description" : "",
                            |                "name" : "",
                            |                "url" : "http://www.eventurl.com"
                            |              },
                            |            "privacy" : "Public",
                            |            "repeats" : "no",
                            |            "start_date" : "2013-06-08 10:00:00",
                            |            "status" : "Live",
                            |            "tags" : "travel, travel writing, masterclasses, short course, ",
                            |            "text_color" : "005580",
                            |            "tickets" : [ { "ticket" : { "currency" : "GBP",
                            |                      "description" : "",
                            |                      "display_price" : "400.00",
                            |                      "end_date" : "2013-06-08 09:30:00",
                            |                      "id" : 132424,
                            |                      "max" : 15,
                            |                      "min" : 1,
                            |                      "name" : "How to launch a food start-up",
                            |                      "price" : "400.00",
                            |                      "start_date" : "2013-04-17 10:20:00",
                            |                      "type" : 0,
                            |                      "visible" : "true"
                            |                    } } ],
                            |            "timezone" : "Europe/London",
                            |            "timezone_offset" : "GMT+0100",
                            |            "title" : "How to launch a food start-up",
                            |            "title_text_color" : "",
                            |            "url" : "https://www.eventurl.com",
                            |            "venue" : { "Lat-Long" : "51.534909 / -0.121693",
                            |                "address" : "Kings Place",
                            |                "address_2" : "90 York Way",
                            |                "city" : "London",
                            |                "country" : "United Kingdom",
                            |                "country_code" : "GB",
                            |                "id" : 645187,
                            |                "latitude" : 51.534908999999999,
                            |                "longitude" : -0.121693,
                            |                "name" : "",
                            |                "postal_code" : "N1 9GU",
                            |                "region" : ""
                            |              }
                            |          } }
                            |] }""".stripMargin('|')



  "MasterClassFeedParser" should "parse out a list of Event JsValues" in {
    val eventBriteFeed: JsValue = Json.parse(rawEventBriteFeed)
  
    val events: Seq[JsValue] = MasterClassesApi.extractEventsFromFeed(eventBriteFeed)
    
    events.size should be (3)
  }
}
