package model

object IpsosTags {

  /*
   * The keys are taken from the section ID returned by CAPI unless otherwise stated
   *
   *  */

  val tags = Map(
    "uk" -> "uk", /* Does not return a section in CAPI */
    "us" -> "us", /* Does not return a section in CAPI */
    "au" -> "au", /* Does not return a section in CAPI */
    "artanddesign" -> "artanddesign",
    "australia-news" -> "australianews",
    "books" -> "books",
    "business" -> "business", /* There isn't a tag specifically for business articles so mapping to business */
    "uk/business" -> "business",
    "us/business" -> "usbusiness",
    "careers" -> "careers",
    "cities" -> "cities",
    "uk/commentisfree" -> "commentisfree",
    "us/commentisfree" -> "uscommentisfree",
    "community" -> "community",
    "crosswords" -> "crosswords",
    "uk/culture" -> "culture", /* There is no US or AU culture tag - should these map to culture? */
    "education" -> "education",
    "uk/environment" -> "environment", /* There is no US or AU environment tag - should these map to environment? */
    "fashion" -> "fashion",
    "uk/film" -> "film", /* There is no US or AU film tag - should these map to film? */
    "food" -> "food",
    "football" -> "football",
    "games" -> "games",
    "global-development" -> "globaldevelopment",
    "guardian-masterclasses" -> "masterclasses",
    "healthcare-network" -> "healthcarenetwork",
    "help" -> "help",
    "housing-network" -> "housingnetwork",
    "inequality" -> "inequality",
    "about" -> "info",
    "law" -> "law",
    "uk/lifeandstyle" -> "lifeandstyle", /* There is no US or AU lifeandstyle tag - should these map to lifeandstyle? */
    "uk/media" -> "media", /* There is no US or AU media tag - should these map to media? */
    "membership" -> "membership",
    "uk/money" -> "money", /* There is no US or AU money tag - should these map to money? */
    "music" -> "music",
    "international" -> "international", /* Does not return a section in CAPI */
    "email-newsletters" -> "emailnewsletters", /* NOT GET GENERATED BY CAPI - NEED TO CREATE THE KEY */
    "observer-food-monthly-awards" -> "ofmawards",
    "observer" -> "observer", /* NOT GET GENERATED BY CAPI - NEED TO CREATE THE KEY (SECTION EXISTS IN JSON) */
    "politics" -> "politics",
    "public-leaders-network" -> "publicleaders",
    "science" -> "science",
    "small-business-network" -> "smallbusiness",
    "society" -> "society",
    "uk/sport" -> "sport", /*This tag should be replaced to free up sport for articles, also no US/AU tags */
    "sport/cricket" -> "cricket", /* This needs to use tag id as section id shows just 'sport' */
    "sport/rugby-union" -> "rugbyunion", /* This needs to use tag id as section id shows just 'sport' */
    "sport/tennis" -> "tennis", /* This needs to use tag id as section id shows just 'sport' */
    "sport/cycling" -> "cycling", /* This needs to use tag id as section id shows just 'sport' */
    "sport/formulaone" -> "formulaone", /* This needs to use tag id as section id shows just 'sport' */
    "sport/golf" -> "golf", /* This needs to use tag id as section id shows just 'sport' */
    "sport/boxing" -> "boxing", /* This needs to use tag id as section id shows just 'sport' */
    "sport/rugbyleague" -> "rugbyleague", /* This needs to use tag id as section id shows just 'sport' */
    "sport/horse-racing" -> "horseracing", /* This needs to use tag id as section id shows just 'sport' */
    "sport/us-sport" -> "ussport", /* This needs to use tag id as section id shows just 'sport' */
    "stage" -> "stage",
    "teacher-network" -> "teachernetwork",
    "uk/technology" -> "technology", /* There is no US or AU technology tag - should these map to technology? */
    "the-guardian-foundation" -> "foundation",
    "theguardian" -> "theguardian",
    "theobserver" -> "theobserver",
    "uk/travel" -> "travel", /* There is no US or AU travel tag - should these map to travel? */
    "tv-and-radio" -> "tvandradio", /* NOT GET GENERATED BY CAPI - NEED TO CREATE THE KEY (SECTION EXISTS IN JSON) */
    "uk-news" -> "uknews",
    "us-news" -> "us-news",
    "voluntary-sector-network" -> "voluntarysector",
    "world" -> "world",
    "world/coronavirus-outbreak" -> "coronavirusoutbreak", /*This needs to use tag id as section id shows just 'world'*/
    "tone/obituaries" -> "obituaries", /* This needs to use tag id as there is no section id */
    "tone/recipes" -> "recipes", /* This needs to use tag id as there is no section id */
    "type/video" -> "video", /* This needs to use tag id as there is no section id */
    "documentaries" -> "documentaries",
    /* NOT GET GENERATED BY CAPI - NEED TO CREATE THE KEY (SECTION EXISTS IN JSON) */
    "type/podcast" -> "podcasts", /* This needs to use tag id as there is no section id */
    "type/gallery" -> "inpictures", /* This needs to use tag id as there is no section id */
    "publication/guardianweekly" -> "weekly", /* This needs to use tag id as there is no section id */
    "guardian-professional" -> "professional",
    "lifeandstyle/health-and-wellbeing" -> "healthandwellbeing",
    /* This needs to use tag id as section id shows just 'lifestyle' */
    "jobs" -> "jobs", /* This may have to be mapped via url */
  )

  def getScriptTag(): Option[String] = {
    Some("Testing")
  }

}
