#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

export PATH=dev/gems/bin:$PATH

bundle install --binstubs dev/gems/bin --path dev/gems

./nave.sh usemain 0.10.24
npm install --loglevel verbose

grunt "$@"
