#!/bin/bash

set -o nounset
set -o errexit

if [ "$teamcity_build_branch_is_default" == "true" ]; then
  echo "Tests will not run on default branch"
  exit
fi

./grunt-tc clean validate test:unit compile
./sbt-tc "project root" test

echo "Tested everything."
