#!/bin/bash

set -o nounset
set -o errexit

echo "##teamcity[progressStart 'Starting grunt tasks']"

./grunt-tc clean validate test:unit compile

echo "##teamcity[progressFinish 'Finished grunt tasks']"

./sbt-tc "project root" test

echo "Tested everything."
