package model
import pa._
import org.joda.time.DateMidnight
import pa.LeagueTableEntry

case class Competition(
    id: String,
    url: String,
    fullName: String,
    shortName: String,
    nation: String,
    startDate: Option[DateMidnight] = None,
    matches: Seq[FootballMatch] = Nil,
    leagueTable: Seq[LeagueTableEntry] = Nil) {

  lazy val hasMatches = matches.nonEmpty
  lazy val hasLeagueTable = leagueTable.nonEmpty

  lazy val matchDates = matches.map(_.date.toDateMidnight).distinct
}

case class Group(round: Option[Round], entries: Seq[LeagueTableEntry])

case class Table(competition: Competition, groups: Seq[Group]) {
  lazy val multiGroup = groups.size > 1
}

object Table {
  def apply(competition: Competition): Table = {
    val groups = competition.leagueTable
      .groupBy(_.round)
      .map { case (round, table) => Group(round, table) }
      // feed consistency around round names and numbers is a little dodgy, hence complex sorting
      .toSeq.sortBy(_.round.map(r => r.name.getOrElse(r.roundNumber)).getOrElse(""))
    Table(competition, groups)
  }
}

case class Team(id: String, url: String, fullName: String, shortName: String)

object Teams {

  val teams: Seq[Team] = Seq(
    Team("94", "/football/celtic", "Celtic", "Celtic"),
    Team("84", "/football/peterborough", "Peterborough", "Peterboro"),
    Team("26303", "/football/realmadrid", "Real Madrid", "Real Madrid"),
    Team("103", "/football/burton-albion", "Albion", "Burton A"),
    Team("79", "", "FC Halifax", "Halifax"),
    Team("15", "/football/nottinghamforest", "Nottm Forest", "Nottm Forest"),
    Team("208", "", "Gainsborough", "Gainsboro"),
    Team("103", "/football/brightonfootball", "Albion", "Brighton"),
    Team("38299", "/football/shakhtardonetsk", "Shakhtar Donetsk", "Shakhtar"),
    Team("6997", "/football/spartakmoscow", "Spartak Moscow", "Spartak"),
    Team("1006", "/football/arsenal", "Arsenal", "Arsenal"),
    Team("215", "/football/morecambe", "Morecambe", "Morecambe"),
    Team("41", "/football/watford", "Watford", "Watford"),
    Team("44", "/football/wolves", "Wolverhampton", "Wolves"),
    Team("23", "/football/bournemouth", "Bournemouth", "Bournemouth"),
    Team("95", "/football/dundee", "Dundee", "Dundee"),
    Team("48", "/football/brentford", "Brentford", "Brentford"),
    Team("51", "/football/bury", "Bury", "Bury"),
    Team("59", "/football/northampton", "Northampton", "Northampton"),
    Team("2", "/football/aston-villa", "Aston Villa", "Aston Villa"),
    Team("26316", "/football/valencia", "Valencia", "Valencia"),
    Team("103", "/football/westbrom", "Albion", "West Brom"),
    Team("104", "/football/alloa", "Alloa", "Alloa"),
    Team("35475", "", "Gloucester", "Gloucester"),
    Team("18890", "", "Guiseley", "Guiseley"),
    Team("17", "/football/sheffieldwednesday", "Sheff Wed", "Sheff Wed"),
    Team("20", "/football/mkdons", "Milton Keynes Dons", "MK Dons"),
    Team("13732", "", "Harrogate Town", "Harrogate"),
    Team("116", "/football/arbroath", "Arbroath", "Arbroath"),
    Team("26316", "/football/antonio-valencia", "Valencia", "---"),
    Team("4", "/football/chelsea", "Chelsea", "Chelsea"),
    Team("34", "/football/plymouthargyle", "Plymouth", "Plymouth"),
    Team("72", "/football/carlisle", "Carlisle", "Carlisle"),
    Team("74", "/football/colchester", "Colchester", "Cochester"),
    Team("95", "/football/dundeeunited", "Dundee", "Dundee Utd"),
    Team("98", "/football/hearts", "Hearts", "Hearts"),
    Team("6", "/football/coventrycity", "Coventry", "Coventry"),
    Team("35", "/football/portvale", "Port Vale", "Port Vale"),
    Team("8", "/football/everton", "Everton", "Everton"),
    Team("55", "/football/fulham", "Fulham", "Fulham"),
    Team("9", "/football/liverpool", "Liverpool", "Liverpool"),
    Team("38276", "/football/zenitstpetersburg", "Zenit St Petersburg", "Zenit"),
    Team("105", "/football/ayr", "Ayr", "Ayr"),
    Team("10186", "", "Hinckley Utd", "Hinckley"),
    Team("19786", "", "Histon", "Histon"),
    Team("37", "/football/sheffieldunited", "Sheff Utd", "Sheff Utd"),
    Team("13361", "", "Oxford City", "Oxford City"),
    Team("179", "", "Dag & Red", "Dag & Red"),
    Team("33", "/football/oxford-united", "Oxford Utd", "Oxford Utd"),
    Team("49567", "", "AFC Telford", "Telford"),
    Team("118", "/football/brechin", "Brechin", "Brechin"),
    Team("26238", "/football/aiksolna", "AIK", "AIK"),
    Team("26313", "/football/athleticbilbao", "Athletic Bilbao", "A Bilbao"),
    Team("31", "/football/newcastleunited", "Newcastle", "Newcastle"),
    Team("85", "/football/rochdale", "Rochdale", "Rochdale"),
    Team("63", "/football/rotherham", "Rotherham", "Rotherham"),
    Team("188", "/football/crawley-town", "Crawley Town", "Crawley"),
    Team("54", "/football/crewealexandra", "Crewe", "Crewe"),
    Team("99", "/football/hibernian", "Hibernian", "Hibernian"),
    Team("123", "/football/kilmarnock", "Kilmarnock", "Kilmarnock"),
    Team("100", "/football/motherwell", "Motherwell", "Motherwell"),
    Team("6794", "/football/doncaster", "Doncaster", "Doncaster"),
    Team("80", "/football/hartlepool", "Hartlepool", "Hartlepool"),
    Team("57", "/football/leytonorient", "Leyton Orient", "Leyton Orient"),
    Team("60", "/football/nottscounty", "Notts County", "Notts County"),
    Team("32", "/football/oldham", "Oldham", "Oldham"),
    Team("88", "/football/southend", "Southend", "Southend"),
    Team("14", "/football/norwichcity", "Norwich", "Norwich"),
    Team("26256", "/football/bayerleverkusen", "Bayer Leverkusen", "Leverkusen"),
    Team("121", "/football/eastfife", "East Fife", "East Fife"),
    Team("1205", "", "Alfreton Town", "Alfreton"),
    Team("473", "", "Solihull Moors", "Solihull"),
    Team("135", "", "Barrow", "Barrow"),
    Team("109", "/football/forfar", "Forfar", "Forfar"),
    Team("26340", "/football/bordeaux", "Bordeaux", "Bordeaux"),
    Team("26282", "/football/clubbrugge", "Club Brugge", "Club Brugge"),
    Team("16", "/football/qpr", "QPR", "QPR"),
    Team("90", "/football/torquay-united", "Torquay", "Torquay"),
    Team("36", "/football/portsmouth", "Portsmouth", "Portsmouth"),
    Team("848", "/football/rosscounty", "Ross County", "Ross County"),
    Team("61", "/football/preston", "Preston", "Preston"),
    Team("153", "/football/wycombe", "Wycombe", "Wycombe"),
    Team("62", "/football/reading", "Reading", "Reading"),
    Team("38305", "/football/dniprodnipropetrovsk", "Dnipro", "Dnipro"),
    Team("127", "/football/stenhousemuir", "Stenhousemuir", "Stenhousemuir"),
    Team("9262", "", "Braintree Town", "Braintree"),
    Team("221", "", "Stalybridge", "Stalybridge"),
    Team("71", "", "Cambridge Utd", "Cambridge"),
    Team("129", "/football/stranraer", "Stranraer", "Stranraer"),
    Team("26412", "/football/fccopenhagen", "FC Copenhagen", "Copenhagen"),
    Team("18", "/football/southampton", "Southampton", "Southampton"),
    Team("92", "/football/york-city", "York", "York"),
    Team("87", "/football/scunthorpe", "Scunthorpe", "Scunthorpe"),
    Team("115", "/football/stjohnstone", "St Johnstone", "St Johnstone"),
    Team("64", "/football/shrewsbury", "Shrewsbury", "Shrewsbury"),
    Team("102", "/football/stmirren", "St Mirren", "St Mirren"),
    Team("92", "/football/newyorkredbulls", "York", "NY Red Bulls"),
    Team("38", "/football/stokecity", "Stoke", "Stoke"),
    Team("26284", "/football/krc-genk", "Genk", "Genk"),
    Team("17635", "/football/annan-athletic", "Annan Athletic", "Annan"),
    Team("10208", "", "Dartford", "Dartford"),
    Team("24612", "", "Vauxhall Motors", "Vauxhall"),
    Team("7813", "", "Ebbsfleet United", "Ebbsfleet"),
    Team("117", "/football/berwick", "Berwick", "Berwick"),
    Team("35999", "/football/hapoeltelaviv", "Hapoel Tel-Aviv", "Hapoel"),
    Team("7520", "/football/helsingborg", "Helsingborgs IF", "Helsingborg"),
    Team("26362", "/football/lazio", "Lazio", "Lazio"),
    Team("39", "/football/sunderland", "Sunderland", "Sunderland"),
    Team("78", "/football/grimsby", "Grimsby", "Grimsby"),
    Team("119", "/football/cowdenbeath", "Cowdenbeath", "Cowdenbeath"),
    Team("1073", "/football/stevenage", "Stevenage", "Stevenage"),
    Team("120", "/football/dumbarton", "Dumbarton", "Dumbarton"),
    Team("97", "/football/dunfermline", "Dunfermline", "Dunfermline"),
    Team("81", "/football/hereford", "Hereford", "Hereford"),
    Team("65", "/football/swansea", "Swansea", "Swansea"),
    Team("37454", "/football/levante", "Levante", "Levante"),
    Team("106", "/football/clyde", "Clyde", "Clyde"),
    Team("5945", "", "Forest Green", "Forest Green"),
    Team("6907", "", "Worcester", "Worcester"),
    Team("209", "", "Gateshead", "Gateshead"),
    Team("122", "/football/eaststirling", "East Stirling", "East Stirling"),
    Team("26345", "/football/lyon", "Lyon", "Lyon"),
    Team("26344", "/football/marseille", "Marseille", "Marseille"),
    Team("26370", "/football/napoli", "Napoli", "Napoli"),
    Team("7013", "/football/panathinaikos", "Panathinaikos", "Panathinaikos"),
    Team("6935", "/football/partizanbelgrade", "Partizan Belgrade", "Partizan"),
    Team("19", "/football/tottenham-hotspur", "Tottenham", "Spurs"),
    Team("10", "/football/lutontown", "Luton", "Luton"),
    Team("108", "/football/falkirk", "Falkirk", "Falkirk"),
    Team("40", "/football/swindon", "Swindon", "Swindon"),
    Team("110", "/football/hamilton", "Hamilton", "Hamilton"),
    Team("111", "/football/livingston", "Livingston", "Livingston"),
    Team("145", "/football/macclesfield", "Macclesfield", "Macclesfield"),
    Team("43", "/football/westhamunited", "West Ham", "West Ham"),
    Team("38336", "/football/viktoria-plzen", "Plzen", "Viktoria"),
    Team("7558", "/football/elgin", "Elgin", "Elgin"),
    Team("212", "", "Hyde", "Hyde"),
    Team("155", "", "Kidderminster", "Kidderminster"),
    Team("82", "", "Lincoln City", "Lincoln"),
    Team("7085", "", "Workington", "Workington"),
    Team("19337", "", "Newport County", "Newport"),
    Team("124", "/football/montrose", "Montrose", "Montrose"),
    Team("26321", "/football/psveindhoven", "PSV", "PSV"),
    Team("68", "/football/wiganathletic", "Wigan", "Wigan"),
    Team("58", "/football/mansfield", "Mansfield", "Mansfield"),
    Team("112", "/football/morton", "Morton", "Morton"),
    Team("66", "/football/tranmere", "Tranmere", "Tranmere"),
    Team("113", "/football/partick", "Partick", "Partick"),
    Team("91", "/football/wrexham", "Wrexham", "Wrexham"),
    Team("21", "/football/barnsley", "Barnsley", "Barnsley"),
    Team("26405", "/football/rapidvienna", "Rapid Vienna", "Rapid Vienna"),
    Team("7596", "/football/peterhead", "Peterhead", "Peterhead"),
    Team("7120", "", "Nuneaton", "Nuneaton"),
    Team("51830", "", "AFC Hornchurch", "Hornchurch"),
    Team("220", "", "Southport", "Southport"),
    Team("126", "/football/queenspark", "Queen's Park", "Queen's Park"),
    Team("26374", "/football/rosenborg", "Rosenborg", "Rosenborg"),
    Team("45", "/football/birminghamcityfc", "Birmingham", "Birmingham"),
    Team("93", "/football/aberdeen", "Aberdeen", "Aberdeen"),
    Team("114", "/football/raith", "Raith", "Raith"),
    Team("67", "/football/walsall", "Walsall", "Walsall"),
    Team("22", "/football/blackburn", "Blackburn", "Blackburn"),
    Team("46218", "/football/rubin-kazan", "Rubin Kazan", "Rubin Kazan"),
    Team("101", "/football/rangers", "Rangers", "Rangers"),
    Team("89", "", "Stockport County", "Stockport"),
    Team("7087", "", "Tamworth", "Tamworth"),
    Team("6889", "", "Basingstoke", "Basingstoke"),
    Team("702", "", "Woking", "Woking"),
    Team("160", "", "Bromley", "Bromley"),
    Team("128", "/football/stirling", "Stirling", "Stirling"),
    Team("7425", "/football/spartaprague", "Sparta Prague", "Sparta Prague"),
    Team("46", "/football/blackpool", "Blackpool", "Blackpool"),
    Team("6870", "/football/yeoviltown", "Yeovil", "Yeovil"),
    Team("47", "/football/boltonwanderers", "Bolton", "Bolton"),
    Team("26268", "/football/sporting-braga", "Sporting", "SC Braga"),
    Team("128", "/football/eaststirling", "Stirling", "East Stirling"),
    Team("186", "", "Chelmsford", "Chelmsford"),
    Team("96", "", "Dundee Utd", "Dundee Utd"),
    Team("58547", "", "Birmingham/Wolves", ""),
    Team("7808", "", "Bath City", "Bath"),
    Team("875", "", "Blyth Spartans", "Blyth"),
    Team("1456", "", "Inverness CT", "Inverness"),
    Team("190", "", "Dorchester", "Dorchester"),
    Team("144", "/football/kettering-town", "Kettering", "Kettering"),
    Team("26268", "/football/sporting-lisbon", "Sporting", "Sporting CP"),
    Team("6795", "/football/brightonfootball", "Brighton", "Brighton"),
    Team("1204", "/football/accringtonstanley", "Accrington Stanley", "Accrington"),
    Team("49", "/football/bristolcity", "Bristol City", "Bristol City"),
    Team("26268", "/football/sportinggijon", "Sporting", "Gijon"),
    Team("9213", "/football/dagenhamandredbridge", "Redbridge", "Dag & Red"),
    Team("191", "", "Dover", "Dover"),
    Team("45938", "", "Airdrie Utd", "Airdrie"),
    Team("61603", "", "Brighton/Wrexham", "???"),
    Team("7066", "", "Billericay", "Billericay"),
    Team("61650", "", "Chelsea/Birmingham", "???"),
    Team("19307", "", "Boreham Wood", "Boreham Wood"),
    Team("125", "", "Queen of South", "QOS FC"),
    Team("13754", "", "Eastbourne Borough", "Eastbourne"),
    Team("26320", "/football/ajax", "Ajax", "Ajax"),
    Team("26360", "/football/udinese", "Udinese", "Udinese"),
    Team("26458", "/football/young-boys-berne", "Young Boys", "Young Boys"),
    Team("70", "/football/burnley", "Burnley", "Burnley"),
    Team("45987", "/football/afc-wimbledon", "AFC Wimbledon", "Wimbledon"),
    Team("52", "/football/cardiffcity", "Cardiff", "Cardiff"),
    Team("27461", "", "Academica", "Academica"),
    Team("11", "/football/manchestercity", "Man City", "Man City"),
    Team("12", "/football/manchester-united", "Man Utd", "Man Utd"),
    Team("26291", "/football/anderlecht", "Anderlecht", "Anderlecht"),
    Team("10894", "", "Eastleigh", "Eastleigh"),
    Team("133", "", "Altrincham", "Altrincham"),
    Team("12712", "", "East Thurrock", "East Thurrock"),
    Team("6245", "", "Bishop's Stortford", "Bishop's Stortford"),
    Team("11667", "", "Farnborough", "t"),
    Team("23510", "", "Havant and W", "Havant"),
    Team("55986", "", "Hayes & Yeading", "Hayes"),
    Team("26300", "/football/barcelona", "Barcelona", "Barcelona"),
    Team("42", "/football/westbrom", "West Brom", "West Brom"),
    Team("43483", "", "AEL", "AEL"),
    Team("3", "/football/charltonathletic", "Charlton", "Charlton"),
    Team("5", "/football/crystalpalace", "Crystal Palace", "C Palace"),
    Team("6886", "/football/aldershottownfootball", "Aldershot", "Aldershot"),
    Team("7", "/football/derbycounty", "Derby", "Derby"),
    Team("42007", "", "Anzhi Makhachkala", "Anzhi"),
    Team("26305", "", "Atletico Madrid", "Atlético"),
    Team("26398", "", "Basle", "Basle"),
    Team("38272", "/football/bate-borisov", "BATE", "BATE"),
    Team("26247", "/football/bayernmunich", "Bayern Munich", "Bayern"),
    Team("26274", "/football/benfica", "Benfica", "Benfica"),
    Team("26261", "/football/borussiadortmund", "Borussia Dortmund", "Dortmund"),
    Team("26269", "/football/sporting-braga", "Braga", "SC Braga"),
    Team("12679", "", "Maidenhead Utd", "Maidenhead"),
    Team("136", "", "Boston Utd", "Boston"),
    Team("9251", "", "Nantwich Town", "Nantwich"),
    Team("10189", "", "Brackley", "Brackley"),
    Team("469", "", "Salisbury", "Salisbury"),
    Team("32166", "/football/dinamozagreb", "Dinamo Zagreb", "D Zagreb"),
    Team("26259", "", "Borussia M'gladbach", "M'gladbach"),
    Team("26451", "/football/galatasaray", "Galatasaray", "Galatasary"),
    Team("7", "/football/series/the-manchester-derby-how-the-teams-compare", "Derby", "???"),
    Team("32309", "", "Hannover 96", "Hannover"),
    Team("134", "/football/barnet", "Barnet", "Barnet"),
    Team("56055", "", "Hapoel Kiryat Shmona", "H Kiryat Shmona"),
    Team("56", "/football/huddersfield", "Huddersfield", "Huddersfield"),
    Team("26359", "/football/juventus", "Juventus", "Juventus"),
    Team("38302", "", "FC Metalist Kharkiv", "FC Metalist"),
    Team("12671", "", "Staines Town", "Staines"),
    Team("13730", "", "Bradford P A", "Bradford PA"),
    Team("61651", "", "Stevenage/Tottenham", "????"),
    Team("53", "", "Chester FC", "Chester"),
    Team("150", "", "Sutton Utd", "Sutton"),
    Team("26322", "", "FC Twente", "Twente"),
    Team("27372", "/football/lille", "Lille", "Lille"),
    Team("26", "/football/hullcity", "Hull", "Hull"),
    Team("6136", "", "Inter Milan", "Inter"),
    Team("7757", "", "Maribor", "Maribor"),
    Team("26267", "", "Maritimo", "Maritimo"),
    Team("24", "/football/bradford", "Bradford", "Bradford City"),
    Team("26377", "", "Molde", "Molde"),
    Team("27", "/football/ipswichtown", "Ipswich", "Ipswich"),
    Team("28", "/football/leedsunited", "Leeds", "Leeds"),
    Team("26351", "/football/montpellier-football-team", "Montpellier", "Montpellier"),
    Team("26449", "", "Fenerbahce", "Fenerbahce"),
    Team("10202", "", "Tonbridge Angels", "Tonbridge"),
    Team("884", "", "Colwyn Bay", "Colwyn"),
    Team("26264", "", "FC Porto", "Porto"),
    Team("478", "", "Stourbridge", "Stourbridge"),
    Team("61625", "", "Sunderland/Middlesbrough", "????"),
    Team("27826", "", "Malaga", "Malaga"),
    Team("10197", "", "Corby", "Corby"),
    Team("26368", "", "AC Milan", "AC Milan"),
    Team("10883", "", "Truro City", "Truro"),
    Team("152", "", "Welling", "Welling"),
    Team("10215", "", "Weston-S-Mare", "Weston-S-Mare"),
    Team("10886", "", "AFC Totton", "Totton"),
    Team("29", "/football/leicestercity", "Leicester", "Leicester"),
    Team("38366", "", "Neftchi", "Neftchi"),
    Team("50", "/football/bristolrovers", "Bristol Rovers", "Bristol Rovers"),
    Team("6901", "", "Steaua Bucuresti", "Steaua"),
    Team("30", "/football/middlesbrough", "Middlesbrough", "Middlesboro"),
    Team("9232", "", "Arlesey", "Arlesey"),
    Team("49647", "", "CFR Cluj-Napoca", "CFR Cluj"),
    Team("18860", "", "Droylsden", "Droylsden"),
    Team("7897", "", "Olympiacos", "Olympiacos"),
    Team("26339", "", "PSG", "PSG"),
    Team("7012", "", "Dynamo Kiev", "Dynamo Kiev"),
    Team("43136", "", "FC Nordsjaelland", "Nordsjaelland"),
    Team("13", "/football/millwall", "Millwall", "Millwall"),
    Team("26250", "", "VfB Stuttgart", "Stuttgart"),
    Team("38429", "", "Videoton FC", "Videoton"),
    Team("184", "/football/burton-albion", "Burton Albion", "Albion"),
    Team("26249", "", "Schalke 04", "Schalke"),
    Team("137", "/football/cheltenham", "Cheltenham", "Cheltenham"),
    Team("73", "/football/chesterfield", "Chesterfield", "Chesterfield"),
    Team("76", "/football/exetercityfc", "Exeter", "Exeter"),
    Team("11899", "/football/fleetwood-town", "Fleetwood Town", "Fleetwood"),
    Team("77", "/football/gillingham", "Gillingham", "Gillingham")
  )

}