// flow-typed signature: a0fc89efcc8ea8890a6ba419f0b7fda2
// flow-typed version: <<STUB>>/amd-to-es6_v^0.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amd-to-es6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amd-to-es6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amd-to-es6/command-line' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amd-to-es6/command-line.js' {
  declare module.exports: $Exports<'amd-to-es6/command-line'>;
}
declare module 'amd-to-es6/index' {
  declare module.exports: $Exports<'amd-to-es6'>;
}
declare module 'amd-to-es6/index.js' {
  declare module.exports: $Exports<'amd-to-es6'>;
}
