// flow-typed signature: 26a183e51aba6864cda1335ebc06f5b0
// flow-typed version: <<STUB>>/amphtml-validator_v^1.0.20/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amphtml-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amphtml-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amphtml-validator/index_test' {
  declare module.exports: any;
}

declare module 'amphtml-validator/postinstall-windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amphtml-validator/index_test.js' {
  declare module.exports: $Exports<'amphtml-validator/index_test'>;
}
declare module 'amphtml-validator/index' {
  declare module.exports: $Exports<'amphtml-validator'>;
}
declare module 'amphtml-validator/index.js' {
  declare module.exports: $Exports<'amphtml-validator'>;
}
declare module 'amphtml-validator/postinstall-windows.js' {
  declare module.exports: $Exports<'amphtml-validator/postinstall-windows'>;
}
