// flow-typed signature: 13dbc0ae9404c2d8c4bd619d0625a86f
// flow-typed version: <<STUB>>/aws-sdk_v~2.0.0-rc4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-sdk/dist-tools/browser-builder' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/service-collector' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/transform' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/api_loader' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/aws' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browser' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/config' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/core' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/cognito_identity_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/credential_provider_chain' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/ec2_metadata_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/environment_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/file_system_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/saml_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/shared_ini_file_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/temporary_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/web_identity_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event_listeners' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/http' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/http/node' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/http/xhr' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/json/builder' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/json/parser' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/metadata_service' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/api' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/collection' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/operation' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/paginator' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/resource_waiter' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/shape' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/param_validator' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/json' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/query' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/rest_json' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/rest_xml' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/rest' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/query/query_param_serializer' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/region_config' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/request' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/resource_waiter' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/response' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/sequential_executor' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/service' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/cloudsearchdomain' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/cognitoidentity' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/dynamodb' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/ec2' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/glacier' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/route53' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/s3' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/sqs' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/sts' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/swf' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/presign' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/request_signer' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/s3' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v2' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v3' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v3https' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v4' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/state_machine' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/util' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/browser_parser' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/builder' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/node_parser' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/translator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-sdk/dist-tools/browser-builder.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/browser-builder'>;
}
declare module 'aws-sdk/dist-tools/service-collector.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/service-collector'>;
}
declare module 'aws-sdk/dist-tools/transform.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/transform'>;
}
declare module 'aws-sdk/index' {
  declare module.exports: $Exports<'aws-sdk'>;
}
declare module 'aws-sdk/index.js' {
  declare module.exports: $Exports<'aws-sdk'>;
}
declare module 'aws-sdk/lib/api_loader.js' {
  declare module.exports: $Exports<'aws-sdk/lib/api_loader'>;
}
declare module 'aws-sdk/lib/aws.js' {
  declare module.exports: $Exports<'aws-sdk/lib/aws'>;
}
declare module 'aws-sdk/lib/browser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browser'>;
}
declare module 'aws-sdk/lib/config.js' {
  declare module.exports: $Exports<'aws-sdk/lib/config'>;
}
declare module 'aws-sdk/lib/core.js' {
  declare module.exports: $Exports<'aws-sdk/lib/core'>;
}
declare module 'aws-sdk/lib/credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials'>;
}
declare module 'aws-sdk/lib/credentials/cognito_identity_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/cognito_identity_credentials'>;
}
declare module 'aws-sdk/lib/credentials/credential_provider_chain.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/credential_provider_chain'>;
}
declare module 'aws-sdk/lib/credentials/ec2_metadata_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/ec2_metadata_credentials'>;
}
declare module 'aws-sdk/lib/credentials/environment_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/environment_credentials'>;
}
declare module 'aws-sdk/lib/credentials/file_system_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/file_system_credentials'>;
}
declare module 'aws-sdk/lib/credentials/saml_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/saml_credentials'>;
}
declare module 'aws-sdk/lib/credentials/shared_ini_file_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/shared_ini_file_credentials'>;
}
declare module 'aws-sdk/lib/credentials/temporary_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/temporary_credentials'>;
}
declare module 'aws-sdk/lib/credentials/web_identity_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/web_identity_credentials'>;
}
declare module 'aws-sdk/lib/event_listeners.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event_listeners'>;
}
declare module 'aws-sdk/lib/http.js' {
  declare module.exports: $Exports<'aws-sdk/lib/http'>;
}
declare module 'aws-sdk/lib/http/node.js' {
  declare module.exports: $Exports<'aws-sdk/lib/http/node'>;
}
declare module 'aws-sdk/lib/http/xhr.js' {
  declare module.exports: $Exports<'aws-sdk/lib/http/xhr'>;
}
declare module 'aws-sdk/lib/json/builder.js' {
  declare module.exports: $Exports<'aws-sdk/lib/json/builder'>;
}
declare module 'aws-sdk/lib/json/parser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/json/parser'>;
}
declare module 'aws-sdk/lib/metadata_service.js' {
  declare module.exports: $Exports<'aws-sdk/lib/metadata_service'>;
}
declare module 'aws-sdk/lib/model/api.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/api'>;
}
declare module 'aws-sdk/lib/model/collection.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/collection'>;
}
declare module 'aws-sdk/lib/model/operation.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/operation'>;
}
declare module 'aws-sdk/lib/model/paginator.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/paginator'>;
}
declare module 'aws-sdk/lib/model/resource_waiter.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/resource_waiter'>;
}
declare module 'aws-sdk/lib/model/shape.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/shape'>;
}
declare module 'aws-sdk/lib/param_validator.js' {
  declare module.exports: $Exports<'aws-sdk/lib/param_validator'>;
}
declare module 'aws-sdk/lib/protocol/json.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/json'>;
}
declare module 'aws-sdk/lib/protocol/query.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/query'>;
}
declare module 'aws-sdk/lib/protocol/rest_json.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/rest_json'>;
}
declare module 'aws-sdk/lib/protocol/rest_xml.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/rest_xml'>;
}
declare module 'aws-sdk/lib/protocol/rest.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/rest'>;
}
declare module 'aws-sdk/lib/query/query_param_serializer.js' {
  declare module.exports: $Exports<'aws-sdk/lib/query/query_param_serializer'>;
}
declare module 'aws-sdk/lib/region_config.js' {
  declare module.exports: $Exports<'aws-sdk/lib/region_config'>;
}
declare module 'aws-sdk/lib/request.js' {
  declare module.exports: $Exports<'aws-sdk/lib/request'>;
}
declare module 'aws-sdk/lib/resource_waiter.js' {
  declare module.exports: $Exports<'aws-sdk/lib/resource_waiter'>;
}
declare module 'aws-sdk/lib/response.js' {
  declare module.exports: $Exports<'aws-sdk/lib/response'>;
}
declare module 'aws-sdk/lib/sequential_executor.js' {
  declare module.exports: $Exports<'aws-sdk/lib/sequential_executor'>;
}
declare module 'aws-sdk/lib/service.js' {
  declare module.exports: $Exports<'aws-sdk/lib/service'>;
}
declare module 'aws-sdk/lib/services.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services'>;
}
declare module 'aws-sdk/lib/services/cloudsearchdomain.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/cloudsearchdomain'>;
}
declare module 'aws-sdk/lib/services/cognitoidentity.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/cognitoidentity'>;
}
declare module 'aws-sdk/lib/services/dynamodb.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/dynamodb'>;
}
declare module 'aws-sdk/lib/services/ec2.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/ec2'>;
}
declare module 'aws-sdk/lib/services/glacier.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/glacier'>;
}
declare module 'aws-sdk/lib/services/route53.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/route53'>;
}
declare module 'aws-sdk/lib/services/s3.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/s3'>;
}
declare module 'aws-sdk/lib/services/sqs.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/sqs'>;
}
declare module 'aws-sdk/lib/services/sts.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/sts'>;
}
declare module 'aws-sdk/lib/services/swf.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/swf'>;
}
declare module 'aws-sdk/lib/signers/presign.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/presign'>;
}
declare module 'aws-sdk/lib/signers/request_signer.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/request_signer'>;
}
declare module 'aws-sdk/lib/signers/s3.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/s3'>;
}
declare module 'aws-sdk/lib/signers/v2.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v2'>;
}
declare module 'aws-sdk/lib/signers/v3.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v3'>;
}
declare module 'aws-sdk/lib/signers/v3https.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v3https'>;
}
declare module 'aws-sdk/lib/signers/v4.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v4'>;
}
declare module 'aws-sdk/lib/state_machine.js' {
  declare module.exports: $Exports<'aws-sdk/lib/state_machine'>;
}
declare module 'aws-sdk/lib/util.js' {
  declare module.exports: $Exports<'aws-sdk/lib/util'>;
}
declare module 'aws-sdk/lib/xml/browser_parser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/browser_parser'>;
}
declare module 'aws-sdk/lib/xml/builder.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/builder'>;
}
declare module 'aws-sdk/lib/xml/node_parser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/node_parser'>;
}
declare module 'aws-sdk/scripts/lib/translator.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/translator'>;
}
