// flow-typed signature: c036048674903d021737dfffe7d81613
// flow-typed version: <<STUB>>/bean_v~1.0.14/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bean'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bean' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bean/bean' {
  declare module.exports: any;
}

declare module 'bean/bean.min' {
  declare module.exports: any;
}

declare module 'bean/buster' {
  declare module.exports: any;
}

declare module 'bean/make/build' {
  declare module.exports: any;
}

declare module 'bean/make/component' {
  declare module.exports: any;
}

declare module 'bean/src/bean' {
  declare module.exports: any;
}

declare module 'bean/src/copyright' {
  declare module.exports: any;
}

declare module 'bean/src/ender' {
  declare module.exports: any;
}

declare module 'bean/tests/add-test' {
  declare module.exports: any;
}

declare module 'bean/tests/clone-test' {
  declare module.exports: any;
}

declare module 'bean/tests/common' {
  declare module.exports: any;
}

declare module 'bean/tests/custom-test' {
  declare module.exports: any;
}

declare module 'bean/tests/custom-types-test' {
  declare module.exports: any;
}

declare module 'bean/tests/delegate-test' {
  declare module.exports: any;
}

declare module 'bean/tests/event-object-test' {
  declare module.exports: any;
}

declare module 'bean/tests/fire-test' {
  declare module.exports: any;
}

declare module 'bean/tests/namespace-test' {
  declare module.exports: any;
}

declare module 'bean/tests/noconflict_fixture' {
  declare module.exports: any;
}

declare module 'bean/tests/noconflict-test' {
  declare module.exports: any;
}

declare module 'bean/tests/remove-test' {
  declare module.exports: any;
}

declare module 'bean/tests/support/syn/browsers' {
  declare module.exports: any;
}

declare module 'bean/tests/support/syn/key' {
  declare module.exports: any;
}

declare module 'bean/tests/support/syn/mouse' {
  declare module.exports: any;
}

declare module 'bean/tests/support/syn/synthetic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bean/bean.js' {
  declare module.exports: $Exports<'bean/bean'>;
}
declare module 'bean/bean.min.js' {
  declare module.exports: $Exports<'bean/bean.min'>;
}
declare module 'bean/buster.js' {
  declare module.exports: $Exports<'bean/buster'>;
}
declare module 'bean/make/build.js' {
  declare module.exports: $Exports<'bean/make/build'>;
}
declare module 'bean/make/component.js' {
  declare module.exports: $Exports<'bean/make/component'>;
}
declare module 'bean/src/bean.js' {
  declare module.exports: $Exports<'bean/src/bean'>;
}
declare module 'bean/src/copyright.js' {
  declare module.exports: $Exports<'bean/src/copyright'>;
}
declare module 'bean/src/ender.js' {
  declare module.exports: $Exports<'bean/src/ender'>;
}
declare module 'bean/tests/add-test.js' {
  declare module.exports: $Exports<'bean/tests/add-test'>;
}
declare module 'bean/tests/clone-test.js' {
  declare module.exports: $Exports<'bean/tests/clone-test'>;
}
declare module 'bean/tests/common.js' {
  declare module.exports: $Exports<'bean/tests/common'>;
}
declare module 'bean/tests/custom-test.js' {
  declare module.exports: $Exports<'bean/tests/custom-test'>;
}
declare module 'bean/tests/custom-types-test.js' {
  declare module.exports: $Exports<'bean/tests/custom-types-test'>;
}
declare module 'bean/tests/delegate-test.js' {
  declare module.exports: $Exports<'bean/tests/delegate-test'>;
}
declare module 'bean/tests/event-object-test.js' {
  declare module.exports: $Exports<'bean/tests/event-object-test'>;
}
declare module 'bean/tests/fire-test.js' {
  declare module.exports: $Exports<'bean/tests/fire-test'>;
}
declare module 'bean/tests/namespace-test.js' {
  declare module.exports: $Exports<'bean/tests/namespace-test'>;
}
declare module 'bean/tests/noconflict_fixture.js' {
  declare module.exports: $Exports<'bean/tests/noconflict_fixture'>;
}
declare module 'bean/tests/noconflict-test.js' {
  declare module.exports: $Exports<'bean/tests/noconflict-test'>;
}
declare module 'bean/tests/remove-test.js' {
  declare module.exports: $Exports<'bean/tests/remove-test'>;
}
declare module 'bean/tests/support/syn/browsers.js' {
  declare module.exports: $Exports<'bean/tests/support/syn/browsers'>;
}
declare module 'bean/tests/support/syn/key.js' {
  declare module.exports: $Exports<'bean/tests/support/syn/key'>;
}
declare module 'bean/tests/support/syn/mouse.js' {
  declare module.exports: $Exports<'bean/tests/support/syn/mouse'>;
}
declare module 'bean/tests/support/syn/synthetic.js' {
  declare module.exports: $Exports<'bean/tests/support/syn/synthetic'>;
}
