// flow-typed signature: 741681e871f1c8064bf952d41a8ffb60
// flow-typed version: <<STUB>>/bs-fullscreen-message_v^1.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-fullscreen-message'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-fullscreen-message' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs-fullscreen-message/client' {
  declare module.exports: any;
}

declare module 'bs-fullscreen-message/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs-fullscreen-message/client.js' {
  declare module.exports: $Exports<'bs-fullscreen-message/client'>;
}
declare module 'bs-fullscreen-message/example.js' {
  declare module.exports: $Exports<'bs-fullscreen-message/example'>;
}
declare module 'bs-fullscreen-message/index' {
  declare module.exports: $Exports<'bs-fullscreen-message'>;
}
declare module 'bs-fullscreen-message/index.js' {
  declare module.exports: $Exports<'bs-fullscreen-message'>;
}
