// flow-typed signature: 80aa343bdcfe0e827801817320f26943
// flow-typed version: <<STUB>>/btoa_v1.1.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'btoa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'btoa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'btoa/bin/btoa' {
  declare module.exports: any;
}

declare module 'btoa/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'btoa/bin/btoa.js' {
  declare module.exports: $Exports<'btoa/bin/btoa'>;
}
declare module 'btoa/index' {
  declare module.exports: $Exports<'btoa'>;
}
declare module 'btoa/index.js' {
  declare module.exports: $Exports<'btoa'>;
}
declare module 'btoa/test.js' {
  declare module.exports: $Exports<'btoa/test'>;
}
