// flow-typed signature: 19198884bd2042249b1fd3134d9cb63d
// flow-typed version: <<STUB>>/circular-dependency-plugin_v3.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'circular-dependency-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'circular-dependency-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'circular-dependency-plugin/__tests__/deps/a' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/b' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/c' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/context/a' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/d' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/e' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/f' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/g' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/h' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/deps/i' {
  declare module.exports: any;
}

declare module 'circular-dependency-plugin/__tests__/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'circular-dependency-plugin/__tests__/deps/a.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/a'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/b.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/b'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/c.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/c'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/context/a.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/context/a'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/d.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/d'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/e.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/e'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/f.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/f'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/g.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/g'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/h.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/h'>;
}
declare module 'circular-dependency-plugin/__tests__/deps/i.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/deps/i'>;
}
declare module 'circular-dependency-plugin/__tests__/index_test.js' {
  declare module.exports: $Exports<'circular-dependency-plugin/__tests__/index_test'>;
}
declare module 'circular-dependency-plugin/index' {
  declare module.exports: $Exports<'circular-dependency-plugin'>;
}
declare module 'circular-dependency-plugin/index.js' {
  declare module.exports: $Exports<'circular-dependency-plugin'>;
}
