// flow-typed signature: a0ec3b221eb8f017f24aff40aaa64c65
// flow-typed version: <<STUB>>/cp-file_v^4.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cp-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cp-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cp-file/cp-file-error' {
  declare module.exports: any;
}

declare module 'cp-file/fs' {
  declare module.exports: any;
}

declare module 'cp-file/progress-emitter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cp-file/cp-file-error.js' {
  declare module.exports: $Exports<'cp-file/cp-file-error'>;
}
declare module 'cp-file/fs.js' {
  declare module.exports: $Exports<'cp-file/fs'>;
}
declare module 'cp-file/index' {
  declare module.exports: $Exports<'cp-file'>;
}
declare module 'cp-file/index.js' {
  declare module.exports: $Exports<'cp-file'>;
}
declare module 'cp-file/progress-emitter.js' {
  declare module.exports: $Exports<'cp-file/progress-emitter'>;
}
