// flow-typed signature: 9afa8a9c5eaca8891f6072a867f95517
// flow-typed version: <<STUB>>/cssstats_v^3.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssstats'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssstats' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssstats/lib/declarations' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-all-font-families' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-all-font-sizes' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-property-resets' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-property-value-count' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-repeated-values' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-sorted-specificity' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-specificity-graph' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-unique-property-count' {
  declare module.exports: any;
}

declare module 'cssstats/lib/get-vendor-prefixed-properties' {
  declare module.exports: any;
}

declare module 'cssstats/lib/media-queries' {
  declare module.exports: any;
}

declare module 'cssstats/lib/rules' {
  declare module.exports: any;
}

declare module 'cssstats/lib/selector-parser' {
  declare module.exports: any;
}

declare module 'cssstats/lib/selectors' {
  declare module.exports: any;
}

declare module 'cssstats/lib/size' {
  declare module.exports: any;
}

declare module 'cssstats/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssstats/index' {
  declare module.exports: $Exports<'cssstats'>;
}
declare module 'cssstats/index.js' {
  declare module.exports: $Exports<'cssstats'>;
}
declare module 'cssstats/lib/declarations.js' {
  declare module.exports: $Exports<'cssstats/lib/declarations'>;
}
declare module 'cssstats/lib/get-all-font-families.js' {
  declare module.exports: $Exports<'cssstats/lib/get-all-font-families'>;
}
declare module 'cssstats/lib/get-all-font-sizes.js' {
  declare module.exports: $Exports<'cssstats/lib/get-all-font-sizes'>;
}
declare module 'cssstats/lib/get-property-resets.js' {
  declare module.exports: $Exports<'cssstats/lib/get-property-resets'>;
}
declare module 'cssstats/lib/get-property-value-count.js' {
  declare module.exports: $Exports<'cssstats/lib/get-property-value-count'>;
}
declare module 'cssstats/lib/get-repeated-values.js' {
  declare module.exports: $Exports<'cssstats/lib/get-repeated-values'>;
}
declare module 'cssstats/lib/get-sorted-specificity.js' {
  declare module.exports: $Exports<'cssstats/lib/get-sorted-specificity'>;
}
declare module 'cssstats/lib/get-specificity-graph.js' {
  declare module.exports: $Exports<'cssstats/lib/get-specificity-graph'>;
}
declare module 'cssstats/lib/get-unique-property-count.js' {
  declare module.exports: $Exports<'cssstats/lib/get-unique-property-count'>;
}
declare module 'cssstats/lib/get-vendor-prefixed-properties.js' {
  declare module.exports: $Exports<'cssstats/lib/get-vendor-prefixed-properties'>;
}
declare module 'cssstats/lib/media-queries.js' {
  declare module.exports: $Exports<'cssstats/lib/media-queries'>;
}
declare module 'cssstats/lib/rules.js' {
  declare module.exports: $Exports<'cssstats/lib/rules'>;
}
declare module 'cssstats/lib/selector-parser.js' {
  declare module.exports: $Exports<'cssstats/lib/selector-parser'>;
}
declare module 'cssstats/lib/selectors.js' {
  declare module.exports: $Exports<'cssstats/lib/selectors'>;
}
declare module 'cssstats/lib/size.js' {
  declare module.exports: $Exports<'cssstats/lib/size'>;
}
declare module 'cssstats/test/test.js' {
  declare module.exports: $Exports<'cssstats/test/test'>;
}
