// flow-typed signature: 7c3d53dfb7643cd407bf9e886cecc0c0
// flow-typed version: <<STUB>>/domready_v^1.0.8/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'domready'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'domready' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'domready/make/build' {
  declare module.exports: any;
}

declare module 'domready/ready' {
  declare module.exports: any;
}

declare module 'domready/ready.min' {
  declare module.exports: any;
}

declare module 'domready/src/ender' {
  declare module.exports: any;
}

declare module 'domready/src/ready' {
  declare module.exports: any;
}

// Filename aliases
declare module 'domready/make/build.js' {
  declare module.exports: $Exports<'domready/make/build'>;
}
declare module 'domready/ready.js' {
  declare module.exports: $Exports<'domready/ready'>;
}
declare module 'domready/ready.min.js' {
  declare module.exports: $Exports<'domready/ready.min'>;
}
declare module 'domready/src/ender.js' {
  declare module.exports: $Exports<'domready/src/ender'>;
}
declare module 'domready/src/ready.js' {
  declare module.exports: $Exports<'domready/src/ready'>;
}
