// flow-typed signature: 710eaa27305ef215771811c574779840
// flow-typed version: <<STUB>>/eslint-plugin-jasmine_v^1.8.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jasmine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jasmine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jasmine/lib/no-dupes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/prohibit' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/missing-expect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/named-spy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/no-assign-spyon' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/no-disabled-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/no-focused-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/no-spec-dupes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/no-suite-callback-args' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/no-suite-dupes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/lib/rules/valid-expect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/missing-expect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/named-spy' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/no-assign-spyon' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/no-disabled-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/no-focused-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/no-spec-dupes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/no-suite-callback-args' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/no-suite-dupes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jasmine/test/rules/valid-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jasmine/index' {
  declare module.exports: $Exports<'eslint-plugin-jasmine'>;
}
declare module 'eslint-plugin-jasmine/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine'>;
}
declare module 'eslint-plugin-jasmine/lib/no-dupes.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/no-dupes'>;
}
declare module 'eslint-plugin-jasmine/lib/prohibit.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/prohibit'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/missing-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/missing-expect'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/named-spy.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/named-spy'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/no-assign-spyon.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/no-assign-spyon'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/no-disabled-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/no-disabled-tests'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/no-focused-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/no-focused-tests'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/no-spec-dupes.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/no-spec-dupes'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/no-suite-callback-args.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/no-suite-callback-args'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/no-suite-dupes.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/no-suite-dupes'>;
}
declare module 'eslint-plugin-jasmine/lib/rules/valid-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/lib/rules/valid-expect'>;
}
declare module 'eslint-plugin-jasmine/test/rules/missing-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/missing-expect'>;
}
declare module 'eslint-plugin-jasmine/test/rules/named-spy.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/named-spy'>;
}
declare module 'eslint-plugin-jasmine/test/rules/no-assign-spyon.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/no-assign-spyon'>;
}
declare module 'eslint-plugin-jasmine/test/rules/no-disabled-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/no-disabled-tests'>;
}
declare module 'eslint-plugin-jasmine/test/rules/no-focused-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/no-focused-tests'>;
}
declare module 'eslint-plugin-jasmine/test/rules/no-spec-dupes.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/no-spec-dupes'>;
}
declare module 'eslint-plugin-jasmine/test/rules/no-suite-callback-args.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/no-suite-callback-args'>;
}
declare module 'eslint-plugin-jasmine/test/rules/no-suite-dupes.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/no-suite-dupes'>;
}
declare module 'eslint-plugin-jasmine/test/rules/valid-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jasmine/test/rules/valid-expect'>;
}
