// flow-typed signature: 350482645d4f2483275fef431618c6b0
// flow-typed version: <<STUB>>/eslint-plugin-flow-header_vhttps://github.com/eirikurn/eslint-plugin-flow-header/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flow-header'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flow-header' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-flow-header/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow-header/lib/rules/flow-header' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow-header/tests/lib/rules/flow-header' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-flow-header/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-header/lib/index'>;
}
declare module 'eslint-plugin-flow-header/lib/rules/flow-header.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-header/lib/rules/flow-header'>;
}
declare module 'eslint-plugin-flow-header/tests/lib/rules/flow-header.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-header/tests/lib/rules/flow-header'>;
}
