// flow-typed signature: 2f0e48291b40464c0f67c94722fc7f6b
// flow-typed version: <<STUB>>/eslint-plugin-guardian-frontend_vfile:dev/eslint-plugin-guardian-frontend/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-guardian-frontend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-guardian-frontend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-guardian-frontend/__tests__/exports-last' {
  declare module.exports: any;
}

declare module 'eslint-plugin-guardian-frontend/__tests__/global-config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-guardian-frontend/__tests__/no-default-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-guardian-frontend/__tests__/no-multiple-classlist-parameter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-guardian-frontend/rules/exports-last' {
  declare module.exports: any;
}

declare module 'eslint-plugin-guardian-frontend/rules/global-config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-guardian-frontend/rules/no-default-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-guardian-frontend/rules/no-multiple-classlist-parameters' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-guardian-frontend/__tests__/exports-last.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/__tests__/exports-last'>;
}
declare module 'eslint-plugin-guardian-frontend/__tests__/global-config.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/__tests__/global-config'>;
}
declare module 'eslint-plugin-guardian-frontend/__tests__/no-default-export.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/__tests__/no-default-export'>;
}
declare module 'eslint-plugin-guardian-frontend/__tests__/no-multiple-classlist-parameter.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/__tests__/no-multiple-classlist-parameter'>;
}
declare module 'eslint-plugin-guardian-frontend/index' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend'>;
}
declare module 'eslint-plugin-guardian-frontend/index.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend'>;
}
declare module 'eslint-plugin-guardian-frontend/rules/exports-last.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/rules/exports-last'>;
}
declare module 'eslint-plugin-guardian-frontend/rules/global-config.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/rules/global-config'>;
}
declare module 'eslint-plugin-guardian-frontend/rules/no-default-export.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/rules/no-default-export'>;
}
declare module 'eslint-plugin-guardian-frontend/rules/no-multiple-classlist-parameters.js' {
  declare module.exports: $Exports<'eslint-plugin-guardian-frontend/rules/no-multiple-classlist-parameters'>;
}
