// flow-typed signature: 471b2b1b181586da15233f97f57b383e
// flow-typed version: <<STUB>>/fastdom_v0.8.5/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fastdom/index' {
  declare module.exports: $Exports<'fastdom'>;
}
declare module 'fastdom/index.js' {
  declare module.exports: $Exports<'fastdom'>;
}
