// flow-typed signature: 47d74797a043ea7d46d67d0a497be0f2
// flow-typed version: <<STUB>>/git-user-name_v^1.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-user-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-user-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-user-name/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-user-name/index' {
  declare module.exports: $Exports<'git-user-name'>;
}
declare module 'git-user-name/index.js' {
  declare module.exports: $Exports<'git-user-name'>;
}
declare module 'git-user-name/utils.js' {
  declare module.exports: $Exports<'git-user-name/utils'>;
}
