// flow-typed signature: ebd12ba7d0bb83e7209cee29ce130d29
// flow-typed version: <<STUB>>/hasha_v^2.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hasha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hasha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hasha/index' {
  declare module.exports: $Exports<'hasha'>;
}
declare module 'hasha/index.js' {
  declare module.exports: $Exports<'hasha'>;
}
