// flow-typed signature: 2149e559f52310440b859a127635b84b
// flow-typed version: <<STUB>>/html5shiv_v^3.7.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html5shiv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html5shiv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html5shiv/dist/html5shiv-printshiv' {
  declare module.exports: any;
}

declare module 'html5shiv/dist/html5shiv-printshiv.min' {
  declare module.exports: any;
}

declare module 'html5shiv/dist/html5shiv' {
  declare module.exports: any;
}

declare module 'html5shiv/dist/html5shiv.min' {
  declare module.exports: any;
}

declare module 'html5shiv/Gruntfile' {
  declare module.exports: any;
}

declare module 'html5shiv/src/html5shiv-printshiv' {
  declare module.exports: any;
}

declare module 'html5shiv/src/html5shiv' {
  declare module.exports: any;
}

declare module 'html5shiv/test/highcharts/highcharts' {
  declare module.exports: any;
}

declare module 'html5shiv/test/jquery-1.7.1/data/test' {
  declare module.exports: any;
}

declare module 'html5shiv/test/jquery-1.7.1/data/testinit' {
  declare module.exports: any;
}

declare module 'html5shiv/test/jquery-1.7.1/data/testrunner' {
  declare module.exports: any;
}

declare module 'html5shiv/test/jquery-1.7.1/data/versioncheck' {
  declare module.exports: any;
}

declare module 'html5shiv/test/jquery-1.7.1/unit/core' {
  declare module.exports: any;
}

declare module 'html5shiv/test/jquery-1.7.1/unit/manipulation' {
  declare module.exports: any;
}

declare module 'html5shiv/test/jquery-1.7.1/unit/traversing' {
  declare module.exports: any;
}

declare module 'html5shiv/test/qunit/qunit' {
  declare module.exports: any;
}

declare module 'html5shiv/test/unit/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html5shiv/dist/html5shiv-printshiv.js' {
  declare module.exports: $Exports<'html5shiv/dist/html5shiv-printshiv'>;
}
declare module 'html5shiv/dist/html5shiv-printshiv.min.js' {
  declare module.exports: $Exports<'html5shiv/dist/html5shiv-printshiv.min'>;
}
declare module 'html5shiv/dist/html5shiv.js' {
  declare module.exports: $Exports<'html5shiv/dist/html5shiv'>;
}
declare module 'html5shiv/dist/html5shiv.min.js' {
  declare module.exports: $Exports<'html5shiv/dist/html5shiv.min'>;
}
declare module 'html5shiv/Gruntfile.js' {
  declare module.exports: $Exports<'html5shiv/Gruntfile'>;
}
declare module 'html5shiv/src/html5shiv-printshiv.js' {
  declare module.exports: $Exports<'html5shiv/src/html5shiv-printshiv'>;
}
declare module 'html5shiv/src/html5shiv.js' {
  declare module.exports: $Exports<'html5shiv/src/html5shiv'>;
}
declare module 'html5shiv/test/highcharts/highcharts.js' {
  declare module.exports: $Exports<'html5shiv/test/highcharts/highcharts'>;
}
declare module 'html5shiv/test/jquery-1.7.1/data/test.js' {
  declare module.exports: $Exports<'html5shiv/test/jquery-1.7.1/data/test'>;
}
declare module 'html5shiv/test/jquery-1.7.1/data/testinit.js' {
  declare module.exports: $Exports<'html5shiv/test/jquery-1.7.1/data/testinit'>;
}
declare module 'html5shiv/test/jquery-1.7.1/data/testrunner.js' {
  declare module.exports: $Exports<'html5shiv/test/jquery-1.7.1/data/testrunner'>;
}
declare module 'html5shiv/test/jquery-1.7.1/data/versioncheck.js' {
  declare module.exports: $Exports<'html5shiv/test/jquery-1.7.1/data/versioncheck'>;
}
declare module 'html5shiv/test/jquery-1.7.1/unit/core.js' {
  declare module.exports: $Exports<'html5shiv/test/jquery-1.7.1/unit/core'>;
}
declare module 'html5shiv/test/jquery-1.7.1/unit/manipulation.js' {
  declare module.exports: $Exports<'html5shiv/test/jquery-1.7.1/unit/manipulation'>;
}
declare module 'html5shiv/test/jquery-1.7.1/unit/traversing.js' {
  declare module.exports: $Exports<'html5shiv/test/jquery-1.7.1/unit/traversing'>;
}
declare module 'html5shiv/test/qunit/qunit.js' {
  declare module.exports: $Exports<'html5shiv/test/qunit/qunit'>;
}
declare module 'html5shiv/test/unit/tests.js' {
  declare module.exports: $Exports<'html5shiv/test/unit/tests'>;
}
