// flow-typed signature: 21fcc4a244247ad0e1487ff6e316f0c6
// flow-typed version: <<STUB>>/jasmine-core_v^2.3.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-core/lib/console/console' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/boot' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/node_example/lib/jasmine_examples/Player' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/node_example/lib/jasmine_examples/Song' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/node_example/spec/helpers/jasmine_examples/SpecHelper' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/node_example/spec/jasmine_examples/PlayerSpec' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/spec/PlayerSpec' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/spec/SpecHelper' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/src/Player' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/example/src/Song' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/jasmine-html' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/jasmine' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/json2' {
  declare module.exports: any;
}

declare module 'jasmine-core/lib/jasmine-core/node_boot' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-core/lib/console/console.js' {
  declare module.exports: $Exports<'jasmine-core/lib/console/console'>;
}
declare module 'jasmine-core/lib/jasmine-core.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core'>;
}
declare module 'jasmine-core/lib/jasmine-core/boot.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/boot'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/node_example/lib/jasmine_examples/Player.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/node_example/lib/jasmine_examples/Player'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/node_example/lib/jasmine_examples/Song.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/node_example/lib/jasmine_examples/Song'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/node_example/spec/helpers/jasmine_examples/SpecHelper.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/node_example/spec/helpers/jasmine_examples/SpecHelper'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/node_example/spec/jasmine_examples/PlayerSpec.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/node_example/spec/jasmine_examples/PlayerSpec'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/spec/PlayerSpec.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/spec/PlayerSpec'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/spec/SpecHelper.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/spec/SpecHelper'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/src/Player.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/src/Player'>;
}
declare module 'jasmine-core/lib/jasmine-core/example/src/Song.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/example/src/Song'>;
}
declare module 'jasmine-core/lib/jasmine-core/jasmine-html.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/jasmine-html'>;
}
declare module 'jasmine-core/lib/jasmine-core/jasmine.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/jasmine'>;
}
declare module 'jasmine-core/lib/jasmine-core/json2.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/json2'>;
}
declare module 'jasmine-core/lib/jasmine-core/node_boot.js' {
  declare module.exports: $Exports<'jasmine-core/lib/jasmine-core/node_boot'>;
}
