// flow-typed signature: 33aa8f7902fe89a03e098a89dd912866
// flow-typed version: <<STUB>>/jest-teamcity-reporter_v^0.6.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-teamcity-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-teamcity-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-teamcity-reporter/index' {
  declare module.exports: $Exports<'jest-teamcity-reporter'>;
}
declare module 'jest-teamcity-reporter/index.js' {
  declare module.exports: $Exports<'jest-teamcity-reporter'>;
}
