// flow-typed signature: 0ece4c879f96071350e313f329ca0be8
// flow-typed version: <<STUB>>/JSON2_v^0.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'JSON2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'JSON2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'JSON2/cycle' {
  declare module.exports: any;
}

declare module 'JSON2/example' {
  declare module.exports: any;
}

declare module 'JSON2/json_parse_state' {
  declare module.exports: any;
}

declare module 'JSON2/json_parse' {
  declare module.exports: any;
}

declare module 'JSON2/json' {
  declare module.exports: any;
}

declare module 'JSON2/json2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'JSON2/cycle.js' {
  declare module.exports: $Exports<'JSON2/cycle'>;
}
declare module 'JSON2/example.js' {
  declare module.exports: $Exports<'JSON2/example'>;
}
declare module 'JSON2/index' {
  declare module.exports: $Exports<'JSON2'>;
}
declare module 'JSON2/index.js' {
  declare module.exports: $Exports<'JSON2'>;
}
declare module 'JSON2/json_parse_state.js' {
  declare module.exports: $Exports<'JSON2/json_parse_state'>;
}
declare module 'JSON2/json_parse.js' {
  declare module.exports: $Exports<'JSON2/json_parse'>;
}
declare module 'JSON2/json.js' {
  declare module.exports: $Exports<'JSON2/json'>;
}
declare module 'JSON2/json2.js' {
  declare module.exports: $Exports<'JSON2/json2'>;
}
