// flow-typed signature: 22cd5b36a7aabbf1188ec0e687b4888d
// flow-typed version: <<STUB>>/karma-requirejs_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-requirejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-requirejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-requirejs/lib/adapter' {
  declare module.exports: any;
}

declare module 'karma-requirejs/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-requirejs/lib/adapter.js' {
  declare module.exports: $Exports<'karma-requirejs/lib/adapter'>;
}
declare module 'karma-requirejs/lib/index.js' {
  declare module.exports: $Exports<'karma-requirejs/lib/index'>;
}
