// flow-typed signature: 64ec8ebdcf8882f80e9f977b107b684e
// flow-typed version: <<STUB>>/karma-jasmine_v^1.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-jasmine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-jasmine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-jasmine/gruntfile' {
  declare module.exports: any;
}

declare module 'karma-jasmine/lib/adapter' {
  declare module.exports: any;
}

declare module 'karma-jasmine/lib/boot' {
  declare module.exports: any;
}

declare module 'karma-jasmine/lib/index' {
  declare module.exports: any;
}

declare module 'karma-jasmine/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-jasmine/gruntfile.js' {
  declare module.exports: $Exports<'karma-jasmine/gruntfile'>;
}
declare module 'karma-jasmine/lib/adapter.js' {
  declare module.exports: $Exports<'karma-jasmine/lib/adapter'>;
}
declare module 'karma-jasmine/lib/boot.js' {
  declare module.exports: $Exports<'karma-jasmine/lib/boot'>;
}
declare module 'karma-jasmine/lib/index.js' {
  declare module.exports: $Exports<'karma-jasmine/lib/index'>;
}
declare module 'karma-jasmine/wallaby.js' {
  declare module.exports: $Exports<'karma-jasmine/wallaby'>;
}
