// flow-typed signature: 823e316330d3ffbfd730a6f9c4cd1246
// flow-typed version: <<STUB>>/karma-script-launcher_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-script-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-script-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-script-launcher/gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-script-launcher/gruntfile.js' {
  declare module.exports: $Exports<'karma-script-launcher/gruntfile'>;
}
declare module 'karma-script-launcher/index' {
  declare module.exports: $Exports<'karma-script-launcher'>;
}
declare module 'karma-script-launcher/index.js' {
  declare module.exports: $Exports<'karma-script-launcher'>;
}
