// flow-typed signature: b0a924de4059d98869e2f4b9997a99f1
// flow-typed version: <<STUB>>/karma-phantomjs-shim_v^1.4.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-phantomjs-shim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-phantomjs-shim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-phantomjs-shim/shim' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-phantomjs-shim/index' {
  declare module.exports: $Exports<'karma-phantomjs-shim'>;
}
declare module 'karma-phantomjs-shim/index.js' {
  declare module.exports: $Exports<'karma-phantomjs-shim'>;
}
declare module 'karma-phantomjs-shim/shim.js' {
  declare module.exports: $Exports<'karma-phantomjs-shim/shim'>;
}
