// flow-typed signature: ec7dfdd892110b5238af8904b03bf840
// flow-typed version: <<STUB>>/lodash.capitalize_v^4.2.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.capitalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.capitalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.capitalize/index' {
  declare module.exports: $Exports<'lodash.capitalize'>;
}
declare module 'lodash.capitalize/index.js' {
  declare module.exports: $Exports<'lodash.capitalize'>;
}
