// flow-typed signature: 6106662c52521f9e349abdf574b72ba0
// flow-typed version: <<STUB>>/lodash.takewhile_v^4.6.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.takewhile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.takewhile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.takewhile/index' {
  declare module.exports: $Exports<'lodash.takewhile'>;
}
declare module 'lodash.takewhile/index.js' {
  declare module.exports: $Exports<'lodash.takewhile'>;
}
