// flow-typed signature: b57ebf8fe1c91d893f82b1c61843db6e
// flow-typed version: <<STUB>>/ophan-tracker-js_v^1.3.6/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ophan-tracker-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ophan-tracker-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ophan-tracker-js/build/fb-instant' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/holidays' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/interactive' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/jobs-courses' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/jobs' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/membership' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.contribution' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.embed' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.fb-instant' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.http-status' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.interactive' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.membership' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.ng' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/ophan.r2' {
  declare module.exports: any;
}

declare module 'ophan-tracker-js/build/witness' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ophan-tracker-js/build/fb-instant.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/fb-instant'>;
}
declare module 'ophan-tracker-js/build/holidays.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/holidays'>;
}
declare module 'ophan-tracker-js/build/interactive.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/interactive'>;
}
declare module 'ophan-tracker-js/build/jobs-courses.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/jobs-courses'>;
}
declare module 'ophan-tracker-js/build/jobs.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/jobs'>;
}
declare module 'ophan-tracker-js/build/membership.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/membership'>;
}
declare module 'ophan-tracker-js/build/ophan.contribution.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.contribution'>;
}
declare module 'ophan-tracker-js/build/ophan.embed.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.embed'>;
}
declare module 'ophan-tracker-js/build/ophan.fb-instant.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.fb-instant'>;
}
declare module 'ophan-tracker-js/build/ophan.http-status.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.http-status'>;
}
declare module 'ophan-tracker-js/build/ophan.interactive.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.interactive'>;
}
declare module 'ophan-tracker-js/build/ophan.membership.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.membership'>;
}
declare module 'ophan-tracker-js/build/ophan.ng.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.ng'>;
}
declare module 'ophan-tracker-js/build/ophan.r2.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/ophan.r2'>;
}
declare module 'ophan-tracker-js/build/witness.js' {
  declare module.exports: $Exports<'ophan-tracker-js/build/witness'>;
}
