// flow-typed signature: 399ef112a150065b6b75dc080c432c19
// flow-typed version: <<STUB>>/pa11y_v^4.10.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pa11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pa11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pa11y/bin/pa11y' {
  declare module.exports: any;
}

declare module 'pa11y/example/actions/index' {
  declare module.exports: any;
}

declare module 'pa11y/example/basic/index' {
  declare module.exports: any;
}

declare module 'pa11y/example/before-script/index' {
  declare module.exports: any;
}

declare module 'pa11y/example/multiple-concurrent/index' {
  declare module.exports: any;
}

declare module 'pa11y/example/multiple/index' {
  declare module.exports: any;
}

declare module 'pa11y/lib/action' {
  declare module.exports: any;
}

declare module 'pa11y/lib/inject' {
  declare module.exports: any;
}

declare module 'pa11y/lib/pa11y' {
  declare module.exports: any;
}

declare module 'pa11y/lib/vendor/HTMLCS' {
  declare module.exports: any;
}

declare module 'pa11y/reporter/cli' {
  declare module.exports: any;
}

declare module 'pa11y/reporter/csv' {
  declare module.exports: any;
}

declare module 'pa11y/reporter/html' {
  declare module.exports: any;
}

declare module 'pa11y/reporter/json' {
  declare module.exports: any;
}

declare module 'pa11y/reporter/markdown' {
  declare module.exports: any;
}

declare module 'pa11y/reporter/tsv' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-actions' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-basic' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-config' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-environment' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-hide-elements' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-ignore' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-level' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-reporter-csv' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-reporter-json' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-reporter-markdown' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-reporter-tsv' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-root-element' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-rules' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-screen-capture' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-selector' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-standard' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli-threshold' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/helper/describe-cli-call' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/mock/website' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/setup' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/lib/action' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/lib/inject' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/lib/pa11y' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/phantom' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/truffler' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/window' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pa11y/bin/pa11y.js' {
  declare module.exports: $Exports<'pa11y/bin/pa11y'>;
}
declare module 'pa11y/example/actions/index.js' {
  declare module.exports: $Exports<'pa11y/example/actions/index'>;
}
declare module 'pa11y/example/basic/index.js' {
  declare module.exports: $Exports<'pa11y/example/basic/index'>;
}
declare module 'pa11y/example/before-script/index.js' {
  declare module.exports: $Exports<'pa11y/example/before-script/index'>;
}
declare module 'pa11y/example/multiple-concurrent/index.js' {
  declare module.exports: $Exports<'pa11y/example/multiple-concurrent/index'>;
}
declare module 'pa11y/example/multiple/index.js' {
  declare module.exports: $Exports<'pa11y/example/multiple/index'>;
}
declare module 'pa11y/lib/action.js' {
  declare module.exports: $Exports<'pa11y/lib/action'>;
}
declare module 'pa11y/lib/inject.js' {
  declare module.exports: $Exports<'pa11y/lib/inject'>;
}
declare module 'pa11y/lib/pa11y.js' {
  declare module.exports: $Exports<'pa11y/lib/pa11y'>;
}
declare module 'pa11y/lib/vendor/HTMLCS.js' {
  declare module.exports: $Exports<'pa11y/lib/vendor/HTMLCS'>;
}
declare module 'pa11y/reporter/cli.js' {
  declare module.exports: $Exports<'pa11y/reporter/cli'>;
}
declare module 'pa11y/reporter/csv.js' {
  declare module.exports: $Exports<'pa11y/reporter/csv'>;
}
declare module 'pa11y/reporter/html.js' {
  declare module.exports: $Exports<'pa11y/reporter/html'>;
}
declare module 'pa11y/reporter/json.js' {
  declare module.exports: $Exports<'pa11y/reporter/json'>;
}
declare module 'pa11y/reporter/markdown.js' {
  declare module.exports: $Exports<'pa11y/reporter/markdown'>;
}
declare module 'pa11y/reporter/tsv.js' {
  declare module.exports: $Exports<'pa11y/reporter/tsv'>;
}
declare module 'pa11y/test/integration/cli-actions.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-actions'>;
}
declare module 'pa11y/test/integration/cli-basic.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-basic'>;
}
declare module 'pa11y/test/integration/cli-config.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-config'>;
}
declare module 'pa11y/test/integration/cli-environment.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-environment'>;
}
declare module 'pa11y/test/integration/cli-hide-elements.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-hide-elements'>;
}
declare module 'pa11y/test/integration/cli-ignore.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-ignore'>;
}
declare module 'pa11y/test/integration/cli-level.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-level'>;
}
declare module 'pa11y/test/integration/cli-reporter-csv.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-reporter-csv'>;
}
declare module 'pa11y/test/integration/cli-reporter-json.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-reporter-json'>;
}
declare module 'pa11y/test/integration/cli-reporter-markdown.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-reporter-markdown'>;
}
declare module 'pa11y/test/integration/cli-reporter-tsv.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-reporter-tsv'>;
}
declare module 'pa11y/test/integration/cli-root-element.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-root-element'>;
}
declare module 'pa11y/test/integration/cli-rules.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-rules'>;
}
declare module 'pa11y/test/integration/cli-screen-capture.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-screen-capture'>;
}
declare module 'pa11y/test/integration/cli-selector.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-selector'>;
}
declare module 'pa11y/test/integration/cli-standard.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-standard'>;
}
declare module 'pa11y/test/integration/cli-threshold.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli-threshold'>;
}
declare module 'pa11y/test/integration/helper/describe-cli-call.js' {
  declare module.exports: $Exports<'pa11y/test/integration/helper/describe-cli-call'>;
}
declare module 'pa11y/test/integration/mock/website.js' {
  declare module.exports: $Exports<'pa11y/test/integration/mock/website'>;
}
declare module 'pa11y/test/integration/setup.js' {
  declare module.exports: $Exports<'pa11y/test/integration/setup'>;
}
declare module 'pa11y/test/unit/lib/action.js' {
  declare module.exports: $Exports<'pa11y/test/unit/lib/action'>;
}
declare module 'pa11y/test/unit/lib/inject.js' {
  declare module.exports: $Exports<'pa11y/test/unit/lib/inject'>;
}
declare module 'pa11y/test/unit/lib/pa11y.js' {
  declare module.exports: $Exports<'pa11y/test/unit/lib/pa11y'>;
}
declare module 'pa11y/test/unit/mock/phantom.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/phantom'>;
}
declare module 'pa11y/test/unit/mock/truffler.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/truffler'>;
}
declare module 'pa11y/test/unit/mock/window.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/window'>;
}
declare module 'pa11y/test/unit/setup.js' {
  declare module.exports: $Exports<'pa11y/test/unit/setup'>;
}
