// flow-typed signature: b6692ddec38f521042b0355151ac5946
// flow-typed version: <<STUB>>/perfectionist_v^2.3.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'perfectionist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'perfectionist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'perfectionist/bin/cmd' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/applyCompact' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/applyCompressed' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/applyExpanded' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/applyTransformFeatures' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/blank' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/deeplyNested' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/getIndent' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/index' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/isSassVariable' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/longest' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/maxSelectorLength' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/prefixedDecls' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/sameLine' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/space' {
  declare module.exports: any;
}

declare module 'perfectionist/dist/walk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'perfectionist/bin/cmd.js' {
  declare module.exports: $Exports<'perfectionist/bin/cmd'>;
}
declare module 'perfectionist/dist/applyCompact.js' {
  declare module.exports: $Exports<'perfectionist/dist/applyCompact'>;
}
declare module 'perfectionist/dist/applyCompressed.js' {
  declare module.exports: $Exports<'perfectionist/dist/applyCompressed'>;
}
declare module 'perfectionist/dist/applyExpanded.js' {
  declare module.exports: $Exports<'perfectionist/dist/applyExpanded'>;
}
declare module 'perfectionist/dist/applyTransformFeatures.js' {
  declare module.exports: $Exports<'perfectionist/dist/applyTransformFeatures'>;
}
declare module 'perfectionist/dist/blank.js' {
  declare module.exports: $Exports<'perfectionist/dist/blank'>;
}
declare module 'perfectionist/dist/deeplyNested.js' {
  declare module.exports: $Exports<'perfectionist/dist/deeplyNested'>;
}
declare module 'perfectionist/dist/getIndent.js' {
  declare module.exports: $Exports<'perfectionist/dist/getIndent'>;
}
declare module 'perfectionist/dist/index.js' {
  declare module.exports: $Exports<'perfectionist/dist/index'>;
}
declare module 'perfectionist/dist/isSassVariable.js' {
  declare module.exports: $Exports<'perfectionist/dist/isSassVariable'>;
}
declare module 'perfectionist/dist/longest.js' {
  declare module.exports: $Exports<'perfectionist/dist/longest'>;
}
declare module 'perfectionist/dist/maxSelectorLength.js' {
  declare module.exports: $Exports<'perfectionist/dist/maxSelectorLength'>;
}
declare module 'perfectionist/dist/prefixedDecls.js' {
  declare module.exports: $Exports<'perfectionist/dist/prefixedDecls'>;
}
declare module 'perfectionist/dist/sameLine.js' {
  declare module.exports: $Exports<'perfectionist/dist/sameLine'>;
}
declare module 'perfectionist/dist/space.js' {
  declare module.exports: $Exports<'perfectionist/dist/space'>;
}
declare module 'perfectionist/dist/walk.js' {
  declare module.exports: $Exports<'perfectionist/dist/walk'>;
}
