// flow-typed signature: 1cd17cd22f2d81a5b48ad2b0dabe0407
// flow-typed version: <<STUB>>/pify_v^2.3.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pify/index' {
  declare module.exports: $Exports<'pify'>;
}
declare module 'pify/index.js' {
  declare module.exports: $Exports<'pify'>;
}
