// flow-typed signature: de49b3562fa14e8bd6835d62ec2bed16
// flow-typed version: <<STUB>>/postcss-pxtorem_v^4.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-pxtorem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-pxtorem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-pxtorem/example/index' {
  declare module.exports: any;
}

declare module 'postcss-pxtorem/lib/filter-prop-list' {
  declare module.exports: any;
}

declare module 'postcss-pxtorem/lib/pixel-unit-regex' {
  declare module.exports: any;
}

declare module 'postcss-pxtorem/spec/pxtorem-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-pxtorem/example/index.js' {
  declare module.exports: $Exports<'postcss-pxtorem/example/index'>;
}
declare module 'postcss-pxtorem/index' {
  declare module.exports: $Exports<'postcss-pxtorem'>;
}
declare module 'postcss-pxtorem/index.js' {
  declare module.exports: $Exports<'postcss-pxtorem'>;
}
declare module 'postcss-pxtorem/lib/filter-prop-list.js' {
  declare module.exports: $Exports<'postcss-pxtorem/lib/filter-prop-list'>;
}
declare module 'postcss-pxtorem/lib/pixel-unit-regex.js' {
  declare module.exports: $Exports<'postcss-pxtorem/lib/pixel-unit-regex'>;
}
declare module 'postcss-pxtorem/spec/pxtorem-spec.js' {
  declare module.exports: $Exports<'postcss-pxtorem/spec/pxtorem-spec'>;
}
