// flow-typed signature: 751362a97ebcbe0cd12565462c25260b
// flow-typed version: <<STUB>>/requirejs_v^2.3.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'requirejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'requirejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'requirejs/bin/r' {
  declare module.exports: any;
}

declare module 'requirejs/require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'requirejs/bin/r.js' {
  declare module.exports: $Exports<'requirejs/bin/r'>;
}
declare module 'requirejs/require.js' {
  declare module.exports: $Exports<'requirejs/require'>;
}
