// flow-typed signature: 9e4eca49008bf6d9621c4e668ed8b25e
// flow-typed version: <<STUB>>/requireindex_v^1.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'requireindex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'requireindex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'requireindex/test/lib/_private' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bam' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bar/f' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bar/fed/again' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bar/fed/ignored' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bar/fed/index' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bar/fed/somemore' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bar/fing' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/bar/index' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/Foo' {
  declare module.exports: any;
}

declare module 'requireindex/test/lib/index' {
  declare module.exports: any;
}

declare module 'requireindex/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'requireindex/index' {
  declare module.exports: $Exports<'requireindex'>;
}
declare module 'requireindex/index.js' {
  declare module.exports: $Exports<'requireindex'>;
}
declare module 'requireindex/test/lib/_private.js' {
  declare module.exports: $Exports<'requireindex/test/lib/_private'>;
}
declare module 'requireindex/test/lib/bam.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bam'>;
}
declare module 'requireindex/test/lib/bar/f.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bar/f'>;
}
declare module 'requireindex/test/lib/bar/fed/again.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bar/fed/again'>;
}
declare module 'requireindex/test/lib/bar/fed/ignored.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bar/fed/ignored'>;
}
declare module 'requireindex/test/lib/bar/fed/index.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bar/fed/index'>;
}
declare module 'requireindex/test/lib/bar/fed/somemore.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bar/fed/somemore'>;
}
declare module 'requireindex/test/lib/bar/fing.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bar/fing'>;
}
declare module 'requireindex/test/lib/bar/index.js' {
  declare module.exports: $Exports<'requireindex/test/lib/bar/index'>;
}
declare module 'requireindex/test/lib/Foo.js' {
  declare module.exports: $Exports<'requireindex/test/lib/Foo'>;
}
declare module 'requireindex/test/lib/index.js' {
  declare module.exports: $Exports<'requireindex/test/lib/index'>;
}
declare module 'requireindex/test/test.js' {
  declare module.exports: $Exports<'requireindex/test/test'>;
}
