// flow-typed signature: b51d2330303d12476cacbdfb7ee18d51
// flow-typed version: <<STUB>>/sass-mq_v~3.3.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-mq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-mq' {
  declare module.exports: any;
}
