// flow-typed signature: 61cb5b985b7dd750ee98eabfb0f2bcd9
// flow-typed version: <<STUB>>/simple-git_v^1.66.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-git/GruntFile' {
  declare module.exports: any;
}

declare module 'simple-git/promise' {
  declare module.exports: any;
}

declare module 'simple-git/src/git' {
  declare module.exports: any;
}

declare module 'simple-git/src/index' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/BranchDeleteSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/BranchSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/CommitSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/DiffSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/FetchSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/FileStatusSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/ListLogSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/PullSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/StatusSummary' {
  declare module.exports: any;
}

declare module 'simple-git/src/responses/TagList' {
  declare module.exports: any;
}

declare module 'simple-git/src/util/exists' {
  declare module.exports: any;
}

declare module 'simple-git/test/integration/include/runner' {
  declare module.exports: any;
}

declare module 'simple-git/test/integration/test-broken-chains' {
  declare module.exports: any;
}

declare module 'simple-git/test/integration/test-parallel-requests' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/include/setup' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-branch' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-catfile' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-clean' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-commands' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-fetch' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-git' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-log' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-pull' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-push' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-raw' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-rebase' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-revert' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-stash' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-status' {
  declare module.exports: any;
}

declare module 'simple-git/test/unit/test-tags' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-git/GruntFile.js' {
  declare module.exports: $Exports<'simple-git/GruntFile'>;
}
declare module 'simple-git/promise.js' {
  declare module.exports: $Exports<'simple-git/promise'>;
}
declare module 'simple-git/src/git.js' {
  declare module.exports: $Exports<'simple-git/src/git'>;
}
declare module 'simple-git/src/index.js' {
  declare module.exports: $Exports<'simple-git/src/index'>;
}
declare module 'simple-git/src/responses/BranchDeleteSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/BranchDeleteSummary'>;
}
declare module 'simple-git/src/responses/BranchSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/BranchSummary'>;
}
declare module 'simple-git/src/responses/CommitSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/CommitSummary'>;
}
declare module 'simple-git/src/responses/DiffSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/DiffSummary'>;
}
declare module 'simple-git/src/responses/FetchSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/FetchSummary'>;
}
declare module 'simple-git/src/responses/FileStatusSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/FileStatusSummary'>;
}
declare module 'simple-git/src/responses/ListLogSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/ListLogSummary'>;
}
declare module 'simple-git/src/responses/PullSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/PullSummary'>;
}
declare module 'simple-git/src/responses/StatusSummary.js' {
  declare module.exports: $Exports<'simple-git/src/responses/StatusSummary'>;
}
declare module 'simple-git/src/responses/TagList.js' {
  declare module.exports: $Exports<'simple-git/src/responses/TagList'>;
}
declare module 'simple-git/src/util/exists.js' {
  declare module.exports: $Exports<'simple-git/src/util/exists'>;
}
declare module 'simple-git/test/integration/include/runner.js' {
  declare module.exports: $Exports<'simple-git/test/integration/include/runner'>;
}
declare module 'simple-git/test/integration/test-broken-chains.js' {
  declare module.exports: $Exports<'simple-git/test/integration/test-broken-chains'>;
}
declare module 'simple-git/test/integration/test-parallel-requests.js' {
  declare module.exports: $Exports<'simple-git/test/integration/test-parallel-requests'>;
}
declare module 'simple-git/test/unit/include/setup.js' {
  declare module.exports: $Exports<'simple-git/test/unit/include/setup'>;
}
declare module 'simple-git/test/unit/test-branch.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-branch'>;
}
declare module 'simple-git/test/unit/test-catfile.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-catfile'>;
}
declare module 'simple-git/test/unit/test-clean.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-clean'>;
}
declare module 'simple-git/test/unit/test-commands.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-commands'>;
}
declare module 'simple-git/test/unit/test-fetch.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-fetch'>;
}
declare module 'simple-git/test/unit/test-git.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-git'>;
}
declare module 'simple-git/test/unit/test-log.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-log'>;
}
declare module 'simple-git/test/unit/test-pull.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-pull'>;
}
declare module 'simple-git/test/unit/test-push.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-push'>;
}
declare module 'simple-git/test/unit/test-raw.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-raw'>;
}
declare module 'simple-git/test/unit/test-rebase.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-rebase'>;
}
declare module 'simple-git/test/unit/test-revert.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-revert'>;
}
declare module 'simple-git/test/unit/test-stash.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-stash'>;
}
declare module 'simple-git/test/unit/test-status.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-status'>;
}
declare module 'simple-git/test/unit/test-tags.js' {
  declare module.exports: $Exports<'simple-git/test/unit/test-tags'>;
}
