// flow-typed signature: 022049ec5cda6266bf1cf66aacf3aeea
// flow-typed version: <<STUB>>/split_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'split'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'split' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'split/examples/pretty' {
  declare module.exports: any;
}

declare module 'split/test/options.asynct' {
  declare module.exports: any;
}

declare module 'split/test/partitioned_unicode' {
  declare module.exports: any;
}

declare module 'split/test/split.asynct' {
  declare module.exports: any;
}

declare module 'split/test/try_catch.asynct' {
  declare module.exports: any;
}

// Filename aliases
declare module 'split/examples/pretty.js' {
  declare module.exports: $Exports<'split/examples/pretty'>;
}
declare module 'split/index' {
  declare module.exports: $Exports<'split'>;
}
declare module 'split/index.js' {
  declare module.exports: $Exports<'split'>;
}
declare module 'split/test/options.asynct.js' {
  declare module.exports: $Exports<'split/test/options.asynct'>;
}
declare module 'split/test/partitioned_unicode.js' {
  declare module.exports: $Exports<'split/test/partitioned_unicode'>;
}
declare module 'split/test/split.asynct.js' {
  declare module.exports: $Exports<'split/test/split.asynct'>;
}
declare module 'split/test/try_catch.asynct.js' {
  declare module.exports: $Exports<'split/test/try_catch.asynct'>;
}
