// flow-typed signature: 73a863810cd90f249a793314b89e13da
// flow-typed version: <<STUB>>/stream-to-observable_v^0.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-to-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-to-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stream-to-observable/index' {
  declare module.exports: $Exports<'stream-to-observable'>;
}
declare module 'stream-to-observable/index.js' {
  declare module.exports: $Exports<'stream-to-observable'>;
}
