// flow-typed signature: bd86bf85476cab241dc01ce2b5b843b9
// flow-typed version: <<STUB>>/video.js_v~5.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'video.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'video.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'video.js/dist/alt/video.novtt' {
  declare module.exports: any;
}

declare module 'video.js/dist/alt/video.novtt.min' {
  declare module.exports: any;
}

declare module 'video.js/dist/ie8/videojs-ie8' {
  declare module.exports: any;
}

declare module 'video.js/dist/ie8/videojs-ie8.min' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ar' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ba' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/bg' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ca' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/cs' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/da' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/de' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/es' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fi' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/hr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/hu' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/it' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ja' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ko' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/nl' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/pt-BR' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ru' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/sr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/sv' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/tr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/uk' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/vi' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/zh-CN' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/zh-TW' {
  declare module.exports: any;
}

declare module 'video.js/dist/video' {
  declare module.exports: any;
}

declare module 'video.js/dist/video.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'video.js/dist/alt/video.novtt.js' {
  declare module.exports: $Exports<'video.js/dist/alt/video.novtt'>;
}
declare module 'video.js/dist/alt/video.novtt.min.js' {
  declare module.exports: $Exports<'video.js/dist/alt/video.novtt.min'>;
}
declare module 'video.js/dist/ie8/videojs-ie8.js' {
  declare module.exports: $Exports<'video.js/dist/ie8/videojs-ie8'>;
}
declare module 'video.js/dist/ie8/videojs-ie8.min.js' {
  declare module.exports: $Exports<'video.js/dist/ie8/videojs-ie8.min'>;
}
declare module 'video.js/dist/lang/ar.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ar'>;
}
declare module 'video.js/dist/lang/ba.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ba'>;
}
declare module 'video.js/dist/lang/bg.js' {
  declare module.exports: $Exports<'video.js/dist/lang/bg'>;
}
declare module 'video.js/dist/lang/ca.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ca'>;
}
declare module 'video.js/dist/lang/cs.js' {
  declare module.exports: $Exports<'video.js/dist/lang/cs'>;
}
declare module 'video.js/dist/lang/da.js' {
  declare module.exports: $Exports<'video.js/dist/lang/da'>;
}
declare module 'video.js/dist/lang/de.js' {
  declare module.exports: $Exports<'video.js/dist/lang/de'>;
}
declare module 'video.js/dist/lang/es.js' {
  declare module.exports: $Exports<'video.js/dist/lang/es'>;
}
declare module 'video.js/dist/lang/fi.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fi'>;
}
declare module 'video.js/dist/lang/fr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fr'>;
}
declare module 'video.js/dist/lang/hr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/hr'>;
}
declare module 'video.js/dist/lang/hu.js' {
  declare module.exports: $Exports<'video.js/dist/lang/hu'>;
}
declare module 'video.js/dist/lang/it.js' {
  declare module.exports: $Exports<'video.js/dist/lang/it'>;
}
declare module 'video.js/dist/lang/ja.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ja'>;
}
declare module 'video.js/dist/lang/ko.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ko'>;
}
declare module 'video.js/dist/lang/nl.js' {
  declare module.exports: $Exports<'video.js/dist/lang/nl'>;
}
declare module 'video.js/dist/lang/pt-BR.js' {
  declare module.exports: $Exports<'video.js/dist/lang/pt-BR'>;
}
declare module 'video.js/dist/lang/ru.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ru'>;
}
declare module 'video.js/dist/lang/sr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/sr'>;
}
declare module 'video.js/dist/lang/sv.js' {
  declare module.exports: $Exports<'video.js/dist/lang/sv'>;
}
declare module 'video.js/dist/lang/tr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/tr'>;
}
declare module 'video.js/dist/lang/uk.js' {
  declare module.exports: $Exports<'video.js/dist/lang/uk'>;
}
declare module 'video.js/dist/lang/vi.js' {
  declare module.exports: $Exports<'video.js/dist/lang/vi'>;
}
declare module 'video.js/dist/lang/zh-CN.js' {
  declare module.exports: $Exports<'video.js/dist/lang/zh-CN'>;
}
declare module 'video.js/dist/lang/zh-TW.js' {
  declare module.exports: $Exports<'video.js/dist/lang/zh-TW'>;
}
declare module 'video.js/dist/video.js' {
  declare module.exports: $Exports<'video.js/dist/video'>;
}
declare module 'video.js/dist/video.min.js' {
  declare module.exports: $Exports<'video.js/dist/video.min'>;
}
