// flow-typed signature: 41d49d08f9be9d4d0982655b509214ed
// flow-typed version: <<STUB>>/webpack-visualizer-plugin_v^0.1.10/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-visualizer-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-visualizer-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-visualizer-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'webpack-visualizer-plugin/lib/pluginmain' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-visualizer-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'webpack-visualizer-plugin/lib/plugin'>;
}
declare module 'webpack-visualizer-plugin/lib/pluginmain.js' {
  declare module.exports: $Exports<'webpack-visualizer-plugin/lib/pluginmain'>;
}
