// flow-typed signature: 0b57e06f2e17de7866b96ef70df89db7
// flow-typed version: <<STUB>>/webshot_v^0.18.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webshot/lib/options' {
  declare module.exports: any;
}

declare module 'webshot/lib/webshot' {
  declare module.exports: any;
}

declare module 'webshot/lib/webshot.phantom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webshot/lib/options.js' {
  declare module.exports: $Exports<'webshot/lib/options'>;
}
declare module 'webshot/lib/webshot.js' {
  declare module.exports: $Exports<'webshot/lib/webshot'>;
}
declare module 'webshot/lib/webshot.phantom.js' {
  declare module.exports: $Exports<'webshot/lib/webshot.phantom'>;
}
