// flow-typed signature: 3322b4454b4517c3c4f0ac4cd9afccf0
// flow-typed version: <<STUB>>/wolfy87-eventemitter_v~4.2.6/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wolfy87-eventemitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wolfy87-eventemitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wolfy87-eventemitter/docs/render' {
  declare module.exports: any;
}

declare module 'wolfy87-eventemitter/EventEmitter' {
  declare module.exports: any;
}

declare module 'wolfy87-eventemitter/EventEmitter.min' {
  declare module.exports: any;
}

declare module 'wolfy87-eventemitter/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wolfy87-eventemitter/docs/render.js' {
  declare module.exports: $Exports<'wolfy87-eventemitter/docs/render'>;
}
declare module 'wolfy87-eventemitter/EventEmitter.js' {
  declare module.exports: $Exports<'wolfy87-eventemitter/EventEmitter'>;
}
declare module 'wolfy87-eventemitter/EventEmitter.min.js' {
  declare module.exports: $Exports<'wolfy87-eventemitter/EventEmitter.min'>;
}
declare module 'wolfy87-eventemitter/tests/tests.js' {
  declare module.exports: $Exports<'wolfy87-eventemitter/tests/tests'>;
}
