package services.dotcomrendering

object PressedContent {
  // Temporarily retain a list of pressed content
  // Ed Tools are supporting us in how to batch/programmatically add tags to pressed articles.
  // When we can tag pressed articles (tracking/dcroptout) then we will:
  // - tag all articles that appear in this list
  // - remove this file entirely
  // - update the ArticleController and the InteractiveController to show pressed pages based on presence of the tag
  // - update the press+clean functionality to automate tagging as part of this process?
  private[this] val content = Set[String](
    // Specified by Visuals UK
    "/world/ng-interactive/2020/nov/12/beirut-blast-a-night-of-horror-captured-by-its-victims",
    "/environment/ng-interactive/2021/feb/23/beneath-the-blue-dive-into-a-dazzling-ocean-under-threat-interactive",
    "/global-development/ng-interactive/2021/jul/28/countdown-to-demolition-the-story-of-al-jalaa-tower-gaza-israel-palestine",
    "/environment/ng-interactive/2021/feb/19/how-fires-have-spread-to-previously-untouched-parts-of-the-world",
    "/us-news/ng-interactive/2020/nov/07/how-did-joe-biden-win-presidency-visual-guide",
    "/world/ng-interactive/2021/apr/21/how-vaccines-are-affecting-covid-19-outbreaks-globally",
    "/world/ng-interactive/2020/jun/25/revealed-data-shows-10-countries-risking-coronavirus-second-wave-as-lockdown-relaxed",
    "/world/ng-interactive/2021/mar/19/revealed-the-data-that-shows-how-covid-bounced-back-after-the-uks-lockdowns",
    "/world/ng-interactive/2021/jun/28/vaccine-inequality-how-rich-countries-cut-covid-deaths-as-poorer-fall-behind",
    "/world/ng-interactive/2021/jan/08/which-countries-have-reported-new-uk-covid-variant",
    "/politics/ng-interactive/2020/nov/25/why-are-fish-a-sticking-point-in-the-brexit-talks",
    "/world/ng-interactive/2020/dec/16/covid-chaos-a-timeline-of-the-uks-handling-of-the-coronavirus-crisis",
    "/us-news/ng-interactive/2020/mar/18/democratic-primary-delegate-count-latest",
    "/us-news/ng-interactive/2020/oct/30/electoral-college-explained-how-biden-faces-an-uphill-battle-in-the-us-election",
    "/us-news/ng-interactive/2020/oct/30/build-your-own-us-election-result-plot-a-win-for-biden-or-trump",
    "/society/ng-interactive/2020/apr/29/how-humans-have-reacted-to-pandemics-through-history-a-visual-guide",
    "/cities/ng-interactive/2020/sep/25/garden-streets-bike-superhighways-cities-future-coronavirus",
    "/world/ng-interactive/2021/jan/25/how-the-arab-spring-unfolded-a-visualisation",
    "/uk-news/ng-interactive/2020/jun/10/mark-duggan-shooting-can-forensic-tech-cast-doubt-on-official-report",
    "/global-development/ng-interactive/2020/jan/15/environment-inequality-hunger-which-global-problems-would-you-fix-first",
    "/environment/ng-interactive/2019/oct/11/guardian-climate-score-how-did-your-mp-do",
    "/environment/ng-interactive/2019/oct/09/half-century-dither-denial-climate-crisis-timeline",
    "/politics/ng-interactive/2019/jul/15/gaffe-prone-arch-schemer-real-boris-johnson-quiz",
    "/environment/ng-interactive/2019/may/17/air-pollution-may-be-damaging-every-organ-and-cell-in-the-body-finds-global-review",
    "/uk-news/ng-interactive/2019/may/06/london-v-england-where-does-your-area-fit-in-the-great-divide",
    "/environment/ng-interactive/2018/dec/21/deadly-weather-the-human-cost-of-2018s-climate-disasters-visual-guide",
    "/us-news/ng-interactive/2018/jul/31/california-fires-wildfires-2018-visual-guide-map",
    "/politics/ng-interactive/2019/feb/15/how-brexit-revealed-four-new-political-factions",
    "/politics/ng-interactive/2018/nov/15/can-you-get-mays-brexit-deal-through-parliament",
    "/world/ng-interactive/2019/may/02/leavers-v-remainers-how-britains-tribes-compare",
    "/politics/ng-interactive/2019/sep/02/a-typical-hour-in-the-life-of-the-irish-border",
    "/politics/ng-interactive/2017/jul/20/where-are-we-up-to-in-these-brexit-talks",
    "/politics/ng-interactive/2016/jun/03/brexit-how-can-the-same-statistics-be-read-so-differently",
    "/politics/ng-interactive/2019/aug/13/how-a-no-deal-brexit-threatens-your-weekly-food-shop",
    "/world/ng-interactive/2020/jun/29/not-fit-for-a-human-coronavirus-in-coxs-bazar-refugee-camps",
    "/world/ng-interactive/2015/aug/26/china-economic-slowdown-world-imports",
    "/world/ng-interactive/2019/may/26/eu-election-results-2019-across-europe",
    "/politics/2016/may/06/holyrood-elections-see-rise-of-team-ruth-and-demise-of-labour-vision",
    "/politics/ng-interactive/2019/dec/13/boris-johnson-achieves-landslide-victory-visual-guide",
    "/us-news/ng-interactive/2018/nov/07/blue-wave-or-blue-ripple-a-visual-guide-to-the-democrats-gains",
    "/cities/ng-interactive/2017/nov/03/three-degree-world-cities-drowned-global-warming",
    "/society/ng-interactive/2015/feb/05/-sp-watch-how-measles-outbreak-spreads-when-kids-get-vaccinated",
    "/world/ng-interactive/2018/jul/03/thailand-cave-rescue-where-were-the-boys-found-and-how-can-they-be-rescued",
    "/world/ng-interactive/2019/mar/06/revealed-the-rise-and-rise-of-populist-rhetoric",
    "/world/ng-interactive/2017/jan/17/missing-flight-mh370-a-visual-guide-to-the-parts-and-debris-found-so-far",
    "/society/ng-interactive/2015/sep/02/unaffordable-country-where-can-you-afford-to-buy-a-house",
    "/world/interactive/2012/may/08/gay-rights-united-states",
    "/technology/ng-interactive/2018/apr/24/bezoss-empire-how-amazon-became-the-worlds-biggest-retailer",
    "/technology/2016/apr/12/the-dark-side-of-guardian-comments",
    "/environment/ng-interactive/2020/may/20/relax-to-the-sounds-of-british-wildlife",
    "/world/ng-interactive/2014/jul/23/a-global-guide-to-the-first-world-war-interactive-documentary",
    "/commentisfree/ng-interactive/2014/aug/29/-sp-mike-brown-stories-racial-profiling-police",
    "/world/ng-interactive/2021/sep/26/german-election-results-exit-poll-and-possible-coalitions",
    "/us-news/ng-interactive/2020/nov/07/how-did-joe-biden-win-presidency-visual-guide",
    "/us-news/ng-interactive/2020/nov/09/senate-and-house-elections-2020-full-results-for-congress",
    "/politics/ng-interactive/2021/jun/22/stormont-where-northern-irish-politics-splits-and-where-it-holds-together",
    "/politics/ng-interactive/2019/dec/12/uk-general-election-2019-full-results-live-labour-conservatives-tories",
    "/cities/ng-interactive/2019/jul/09/cities-from-scratch-100-and-counting-new-cities-rise-from-the-desert-jungle-and-sea",
    "/politics/ng-interactive/2021/may/06/2021-elections-results-may-local-scottish-welsh-polls",
    "/world/ng-interactive/2020/jun/26/nine-points-up-on-europe-data-shows-uk-increase-in-lgbtq-harassment",
    "/world/ng-interactive/2020/apr/09/how-coronavirus-spread-across-the-globe-visualised",
    "/politics/ng-interactive/2019/may/02/local-elections-2019-live-results-for-english-councils",
    "/world/ng-interactive/2018/mar/05/italian-elections-2018-full-results-renzi-berlusconi",
    "/us-news/ng-interactive/2020/dec/08/us-election-results-2020-joe-biden-defeats-donald-trump-to-win-presidency",
    "/environment/ng-interactive/2021/apr/29/visualised-glaciers-now-and-then",
    "/environment/ng-interactive/2015/nov/26/the-mekong-river-stories-from-the-heart-of-the-climate-crisis-interactive",
    "/football/ng-interactive/2014/dec/21/the-top-100-footballers-2014-interactive",
    "/uk-news/ng-interactive/2014/feb/11/britain-100-years-of-conflict",
    // Specified by Newsletters UK
    "/info/ng-interactive/2017/may/05/sign-up-for-the-long-read-email",
    "/info/ng-interactive/2017/mar/06/sign-up-for-the-sleeve-notes-email",
    "/info/ng-interactive/2017/mar/30/sign-up-for-the-bookmarks-email",
    "/info/ng-interactive/2016/dec/07/sign-up-for-the-flyer",
    "/info/ng-interactive/2017/jul/25/sign-up-for-the-fashion-statement-email",
    "/info/ng-interactive/2017/jan/12/sign-up-for-the-guardian-opinion-email",
    // Specified by Design UK
    "/money/ng-interactive/2020/may/30/cash-coronavirus-financial-shape-money",
    "/world/ng-interactive/2020/jul/11/black-history-timeline",
    "/lifeandstyle/ng-interactive/2019/apr/09/raf-simons-on-life-after-calvin-klein-ive-never-defined-myself-as-a-fashion-designer",
    "/world/ng-interactive/2020/apr/08/coronavirus-100-days-that-changed-the-world",
    "/media/ng-interactive/2021/may/07/we-were-there-the-guardians-most-memorable-journalism-over-200-years",
    "/commentisfree/ng-interactive/2019/dec/10/the-guardian-view-on-general-election-2019-a-fleeting-chance-to-stop-boris-johnson-in-his-tracks",
    "/us-news/ng-interactive/2018/nov/17/michelle-obama-interviewed-miley-cyrus-katy-perry-becoming",
    "/lifeandstyle/ng-interactive/2018/apr/21/great-lengths",
    "/books/ng-interactive/2018/aug/18/barack-obama-reveals-how-letters-from-the-american-people-shaped-his-presidency-interview",
    "/film/ng-interactive/2017/oct/14/three-exhausting-weeks-an-exclusive-short-story-from-tom-hanks-uncommon-type",
    "/food/ng-interactive/2020/feb/16/50-things-we-love-in-the-world-of-food-right-now",
    "/food/ng-interactive/2019/feb/24/the-ofm-50-2019-everything-we-love-in-the-world-of-food-right-now",
    "/global-development/ng-interactive/2018/sep/07/women-gorongosa-national-park-healing-scars-of-war-mozambique",
    "/books/ng-interactive/2018/dec/01/guardian-review-best-books-of-2018",
    "/travel/ng-interactive/2019/jan/05/where-to-go-on-holiday-in-2019-the-hotlist",
    "/politics/ng-interactive/2019/jul/17/boris-johnson-gaff-prone-character-controversies",
    "/lifeandstyle/ng-interactive/2019/apr/07/green-design-waste-not-want",
    "/lifeandstyle/ng-interactive/2019/apr/08/madelon-vriesendorp-architectures-lost-heroine",
    "/artanddesign/ng-interactive/2020/jan/12/mole-man-and-me-sue-webster-artist-home-david-adjaye",
    "/uk-news/ng-interactive/2020/jul/29/young-british-black-voices-behind-uk-anti-racism-protests-george-floyd",
    "/global-development/ng-interactive/2018/aug/20/lost-tribes-1000km-rainforest-mission-amazon-village-brazil",
    "/info/ng-interactive/2018/jul/24/working-report",
    "/world/ng-interactive/2020/dec/14/coronavirus-2020-timeline-covid-19",
    "/politics/ng-interactive/2020/feb/01/britain-and-the-eu-a-timeline",
    "/politics/ng-interactive/2019/dec/14/johnson-ascendant-your-general-election-recap",
    "/us-news/ng-interactive/2019/sep/13/edward-snowden-interview-whistleblowing-russia-ai-permanent-record",
    "/technology/ng-interactive/2019/jun/22/the-rise-of-the-deepfake-and-the-threat-to-democracy",
    "/books/ng-interactive/2016/sep/03/tinker-tailor-writer-spy-the-many-lives-of-john-le-carre-in-his-own-words",
    "/politics/ng-interactive/2019/jul/23/brexit-under-boris-johnson-the-scenarios",
    "/world/ng-interactive/2020/mar/02/europeans-one-right-answer-by-alice-zeniter-starring-sabrina-ouazani",
    "/world/ng-interactive/2020/apr/09/sound-of-icebergs-melting-journey-into-antarctic-jonathan-watts-greenpeace",
    "/world/ng-interactive/2020/jun/01/climate-protesters-german-village-coal-still-king",
    "/environment/ng-interactive/2020/jul/29/australia-after-the-bushfires-aoe",
    "/environment/ng-interactive/2020/oct/05/the-guardian-climate-pledge-2020-environment-emergency-carbon-emissions",
    "/info/ng-interactive/2019/dec/19/working-report",
    "/info/ng-interactive/2020/dec/21/the-guardian-in-2020",
    "/books/ng-interactive/2020/nov/07/caught-in-times-current-margaret-atwood-on-grief-poetry-and-the-past-four-years",
    "/us-news/ng-interactive/2020/aug/11/lost-on-the-frontline-covid-19-coronavirus-us-healthcare-workers-deaths-database",
    "/us-news/ng-interactive/2020/dec/22/why-were-counting-every-us-healthcare-worker-who-dies-from-coronavirus",
    "/media/ng-interactive/2021/may/05/guardian-200-timelines",
    "/world/ng-interactive/2021/jun/02/so-many-revolutions-to-lead-europe-generation-z-on-their-post-covid-future",
    "/tv-and-radio/ng-interactive/2021/jul/01/whats-on-netflix-and-amazon-this-month-july",
    "/world/ng-interactive/2020/oct/15/justice-on-trial-three-years-after-murder-daphne-caruana-galizia",
    "/music/ng-interactive/2020/oct/07/the-months-best-album-reviews",
    "/fashion/ng-interactive/2020/jan/12/gran-designs-maximal-80s-style-in-dressing-and-decor",
    "/artanddesign/ng-interactive/2020/jan/12/art-into-nature-nature-into-art-cesar-manrique-the-architect-of-lanzarote",
    "/environment/ng-interactive/2019/oct/16/the-guardians-climate-pledge-2019",
    "/lifeandstyle/ng-interactive/2017/feb/19/the-5th-annual-ofm-50-what-we-love-about-food-in-2017",
    "/lifeandstyle/ng-interactive/2018/feb/25/the-ofm-50-everything-we-love-in-the-world-of-food-right-now",
    "/cities/ng-interactive/2016/nov/10/subterranean-london",
    // articles
    "/travel/2015/dec/03/machu-picchu-google-street-view-peru",
    "/membership/2017/jan/23/saving-retirement-pension-generation-old-age",
    "/us-news/2015/jun/05/black-women-police-killing-tanisha-anderson",
    "/australia-news/2019/dec/18/too-hot-for-humans-first-nations-people-fear-becoming-australias-first-climate-refugees",
    "/whats-in-your-blood-/2018/oct/11/ancestry-search-unexpected-discovery",
  )

  def isPressed(path: String): Boolean = content.contains(path)
}
