// flow-typed signature: 9f52a94b46f5888d5c39363c29790fb7
// flow-typed version: <<STUB>>/babel-plugin-provide-modules_v^1.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-provide-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-provide-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-provide-modules/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-provide-modules/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-provide-modules/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-provide-modules/lib/index'>;
}
declare module 'babel-plugin-provide-modules/test/index.test.js' {
  declare module.exports: $Exports<'babel-plugin-provide-modules/test/index.test'>;
}
