// flow-typed signature: 4e97248cad3c3e8ff96dc6712f94f8e4
// flow-typed version: <<STUB>>/babel-plugin-preact-require_v^1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-preact-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-preact-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-preact-require/built-examples/stateless-component1' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/built-examples/stateless-component2' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/built-examples/with-imported-react' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/built-examples/without-imported-react' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/built-examples/without-jsx' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/examples/stateless-component1' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/examples/stateless-component2' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/examples/with-imported-react' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/examples/without-imported-react' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/examples/without-jsx' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-preact-require/test/indexTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-preact-require/built-examples/stateless-component1.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/built-examples/stateless-component1'>;
}
declare module 'babel-plugin-preact-require/built-examples/stateless-component2.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/built-examples/stateless-component2'>;
}
declare module 'babel-plugin-preact-require/built-examples/with-imported-react.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/built-examples/with-imported-react'>;
}
declare module 'babel-plugin-preact-require/built-examples/without-imported-react.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/built-examples/without-imported-react'>;
}
declare module 'babel-plugin-preact-require/built-examples/without-jsx.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/built-examples/without-jsx'>;
}
declare module 'babel-plugin-preact-require/examples/stateless-component1.jsx' {
  declare module.exports: $Exports<'babel-plugin-preact-require/examples/stateless-component1'>;
}
declare module 'babel-plugin-preact-require/examples/stateless-component2.jsx' {
  declare module.exports: $Exports<'babel-plugin-preact-require/examples/stateless-component2'>;
}
declare module 'babel-plugin-preact-require/examples/with-imported-react.jsx' {
  declare module.exports: $Exports<'babel-plugin-preact-require/examples/with-imported-react'>;
}
declare module 'babel-plugin-preact-require/examples/without-imported-react.jsx' {
  declare module.exports: $Exports<'babel-plugin-preact-require/examples/without-imported-react'>;
}
declare module 'babel-plugin-preact-require/examples/without-jsx.jsx' {
  declare module.exports: $Exports<'babel-plugin-preact-require/examples/without-jsx'>;
}
declare module 'babel-plugin-preact-require/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/lib/index'>;
}
declare module 'babel-plugin-preact-require/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/src/index'>;
}
declare module 'babel-plugin-preact-require/test/indexTest.js' {
  declare module.exports: $Exports<'babel-plugin-preact-require/test/indexTest'>;
}
