// flow-typed signature: e7fbd835b1b5b15da96eb4bbc0013bb2
// flow-typed version: <<STUB>>/check-node-version_v^2.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'check-node-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'check-node-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'check-node-version/bin' {
  declare module.exports: any;
}

declare module 'check-node-version/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'check-node-version/bin.js' {
  declare module.exports: $Exports<'check-node-version/bin'>;
}
declare module 'check-node-version/index' {
  declare module.exports: $Exports<'check-node-version'>;
}
declare module 'check-node-version/index.js' {
  declare module.exports: $Exports<'check-node-version'>;
}
declare module 'check-node-version/test.js' {
  declare module.exports: $Exports<'check-node-version/test'>;
}
