// flow-typed signature: 598b1108d8b89fe3f753971465d9598f
// flow-typed version: <<STUB>>/gzip-size-cli_v^2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gzip-size-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gzip-size-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gzip-size-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gzip-size-cli/cli.js' {
  declare module.exports: $Exports<'gzip-size-cli/cli'>;
}
