// flow-typed signature: c9bc15025e26f5fcc3bac2d0ac9defa3
// flow-typed version: <<STUB>>/preact-svg-loader_v^0.2.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-svg-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-svg-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-svg-loader/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-svg-loader/src/index.js' {
  declare module.exports: $Exports<'preact-svg-loader/src/index'>;
}
