// flow-typed signature: 413f576b186556790f27bbe9022e2680
// flow-typed version: <<STUB>>/preact-render-to-string_v^3.6.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-render-to-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-render-to-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-render-to-string/dist/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/rollup.config' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/polyfills' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/util' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/test/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/test/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/test/pretty' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/test/render' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/test/shallowRender' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-render-to-string/dist/index.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/index'>;
}
declare module 'preact-render-to-string/dist/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/jsx'>;
}
declare module 'preact-render-to-string/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/jsx'>;
}
declare module 'preact-render-to-string/rollup.config.js' {
  declare module.exports: $Exports<'preact-render-to-string/rollup.config'>;
}
declare module 'preact-render-to-string/src/index.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/index'>;
}
declare module 'preact-render-to-string/src/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/jsx'>;
}
declare module 'preact-render-to-string/src/polyfills.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/polyfills'>;
}
declare module 'preact-render-to-string/src/util.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/util'>;
}
declare module 'preact-render-to-string/test/index.js' {
  declare module.exports: $Exports<'preact-render-to-string/test/index'>;
}
declare module 'preact-render-to-string/test/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/test/jsx'>;
}
declare module 'preact-render-to-string/test/pretty.js' {
  declare module.exports: $Exports<'preact-render-to-string/test/pretty'>;
}
declare module 'preact-render-to-string/test/render.js' {
  declare module.exports: $Exports<'preact-render-to-string/test/render'>;
}
declare module 'preact-render-to-string/test/shallowRender.js' {
  declare module.exports: $Exports<'preact-render-to-string/test/shallowRender'>;
}
