// flow-typed signature: 994ecf6210fa5b1419d9207163c1f311
// flow-typed version: <<STUB>>/styletron-loader_v^0.6.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-loader/parser' {
  declare module.exports: any;
}

declare module 'styletron-loader/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-loader/index' {
  declare module.exports: $Exports<'styletron-loader'>;
}
declare module 'styletron-loader/index.js' {
  declare module.exports: $Exports<'styletron-loader'>;
}
declare module 'styletron-loader/parser.js' {
  declare module.exports: $Exports<'styletron-loader/parser'>;
}
declare module 'styletron-loader/util.js' {
  declare module.exports: $Exports<'styletron-loader/util'>;
}
