package idapiclient

import common.ExecutionContexts
import client.connection.dispatch.DispatchAsyncHttpClient
import utils.SafeLogging


class IdDispatchAsyncHttpClient extends DispatchAsyncHttpClient with ExecutionContexts with SafeLogging
