// flow-typed signature: f7737126e52cdf079761f2461ce6f443
// flow-typed version: <<STUB>>/@guardian/guui_v1.4.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@guardian/guui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@guardian/guui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@guardian/guui/dist/index' {
  declare module.exports: any;
}

declare module '@guardian/guui/dist/lib/loaders/guui-css-loader' {
  declare module.exports: any;
}

declare module '@guardian/guui/dist/lib/loaders/guui-svg-loader' {
  declare module.exports: any;
}

declare module '@guardian/guui/lib/loaders/guui-css-loader' {
  declare module.exports: any;
}

declare module '@guardian/guui/lib/loaders/guui-svg-loader' {
  declare module.exports: any;
}

declare module '@guardian/guui/src/h' {
  declare module.exports: any;
}

declare module '@guardian/guui/src/index' {
  declare module.exports: any;
}

declare module '@guardian/guui/src/server' {
  declare module.exports: any;
}

declare module '@guardian/guui/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@guardian/guui/dist/index.js' {
  declare module.exports: $Exports<'@guardian/guui/dist/index'>;
}
declare module '@guardian/guui/dist/lib/loaders/guui-css-loader.js' {
  declare module.exports: $Exports<'@guardian/guui/dist/lib/loaders/guui-css-loader'>;
}
declare module '@guardian/guui/dist/lib/loaders/guui-svg-loader.js' {
  declare module.exports: $Exports<'@guardian/guui/dist/lib/loaders/guui-svg-loader'>;
}
declare module '@guardian/guui/lib/loaders/guui-css-loader.js' {
  declare module.exports: $Exports<'@guardian/guui/lib/loaders/guui-css-loader'>;
}
declare module '@guardian/guui/lib/loaders/guui-svg-loader.js' {
  declare module.exports: $Exports<'@guardian/guui/lib/loaders/guui-svg-loader'>;
}
declare module '@guardian/guui/src/h.jsx' {
  declare module.exports: $Exports<'@guardian/guui/src/h'>;
}
declare module '@guardian/guui/src/index.jsx' {
  declare module.exports: $Exports<'@guardian/guui/src/index'>;
}
declare module '@guardian/guui/src/server.js' {
  declare module.exports: $Exports<'@guardian/guui/src/server'>;
}
declare module '@guardian/guui/webpack.config.js' {
  declare module.exports: $Exports<'@guardian/guui/webpack.config'>;
}
