// flow-typed signature: 25ba8a14f945746ceba2f707c352ca62
// flow-typed version: <<STUB>>/babel-plugin-add-react-displayname_v^0.0.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-add-react-displayname'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-add-react-displayname' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-add-react-displayname/test/fixtures/arrowFun/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/arrowFun/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/classComponents/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/classComponents/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/createClass/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/createClass/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/decorators/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/decorators/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/exportDefaultAnon/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/exportDefaultAnon/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/functionExpr/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/functionExpr/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/knownComponents/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/knownComponents/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/passThrough/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/fixtures/passThrough/input' {
  declare module.exports: any;
}

declare module 'babel-plugin-add-react-displayname/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-add-react-displayname/index' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname'>;
}
declare module 'babel-plugin-add-react-displayname/index.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/arrowFun/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/arrowFun/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/arrowFun/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/arrowFun/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/classComponents/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/classComponents/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/classComponents/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/classComponents/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/createClass/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/createClass/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/createClass/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/createClass/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/decorators/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/decorators/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/decorators/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/decorators/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/exportDefaultAnon/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/exportDefaultAnon/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/exportDefaultAnon/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/exportDefaultAnon/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/functionExpr/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/functionExpr/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/functionExpr/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/functionExpr/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/knownComponents/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/knownComponents/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/knownComponents/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/knownComponents/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/passThrough/expected.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/passThrough/expected'>;
}
declare module 'babel-plugin-add-react-displayname/test/fixtures/passThrough/input.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/fixtures/passThrough/input'>;
}
declare module 'babel-plugin-add-react-displayname/test/tests.js' {
  declare module.exports: $Exports<'babel-plugin-add-react-displayname/test/tests'>;
}
