// flow-typed signature: e7ca78a941069a071b28350648503330
// flow-typed version: <<STUB>>/concurrently_v^3.5.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concurrently/src/main' {
  declare module.exports: any;
}

declare module 'concurrently/test/support/signal' {
  declare module.exports: any;
}

declare module 'concurrently/test/test-functional' {
  declare module.exports: any;
}

declare module 'concurrently/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concurrently/src/main.js' {
  declare module.exports: $Exports<'concurrently/src/main'>;
}
declare module 'concurrently/test/support/signal.js' {
  declare module.exports: $Exports<'concurrently/test/support/signal'>;
}
declare module 'concurrently/test/test-functional.js' {
  declare module.exports: $Exports<'concurrently/test/test-functional'>;
}
declare module 'concurrently/test/utils.js' {
  declare module.exports: $Exports<'concurrently/test/utils'>;
}
