// flow-typed signature: 464fcdc6bbeab32d3f582740c1a24daf
// flow-typed version: <<STUB>>/emotion_v^7.3.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion/babel' {
  declare module.exports: any;
}

declare module 'emotion/dist/DO-NOT-USE.min' {
  declare module.exports: any;
}

declare module 'emotion/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'emotion/dist/index.es' {
  declare module.exports: any;
}

declare module 'emotion/macro' {
  declare module.exports: any;
}

declare module 'emotion/react/index' {
  declare module.exports: any;
}

declare module 'emotion/react/macro' {
  declare module.exports: any;
}

declare module 'emotion/server' {
  declare module.exports: any;
}

declare module 'emotion/src/index' {
  declare module.exports: any;
}

declare module 'emotion/src/sheet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion/babel.js' {
  declare module.exports: $Exports<'emotion/babel'>;
}
declare module 'emotion/dist/DO-NOT-USE.min.js' {
  declare module.exports: $Exports<'emotion/dist/DO-NOT-USE.min'>;
}
declare module 'emotion/dist/index.cjs.js' {
  declare module.exports: $Exports<'emotion/dist/index.cjs'>;
}
declare module 'emotion/dist/index.es.js' {
  declare module.exports: $Exports<'emotion/dist/index.es'>;
}
declare module 'emotion/macro.js' {
  declare module.exports: $Exports<'emotion/macro'>;
}
declare module 'emotion/react/index.js' {
  declare module.exports: $Exports<'emotion/react/index'>;
}
declare module 'emotion/react/macro.js' {
  declare module.exports: $Exports<'emotion/react/macro'>;
}
declare module 'emotion/server.js' {
  declare module.exports: $Exports<'emotion/server'>;
}
declare module 'emotion/src/index.js' {
  declare module.exports: $Exports<'emotion/src/index'>;
}
declare module 'emotion/src/sheet.js' {
  declare module.exports: $Exports<'emotion/src/sheet'>;
}
