// flow-typed signature: 5ab0d4c21e9b973879d01719db8c0acd
// flow-typed version: <<STUB>>/emotion-server_v^7.3.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-server/lib/index' {
  declare module.exports: any;
}

declare module 'emotion-server/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-server/lib/index.js' {
  declare module.exports: $Exports<'emotion-server/lib/index'>;
}
declare module 'emotion-server/src/index.js' {
  declare module.exports: $Exports<'emotion-server/src/index'>;
}
