// flow-typed signature: ab3936a7bb850b8cdbec4ca9cccae9f2
// flow-typed version: <<STUB>>/htmltojsx_v^0.2.6/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmltojsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmltojsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'htmltojsx/gulpfile' {
  declare module.exports: any;
}

declare module 'htmltojsx/src/cli' {
  declare module.exports: any;
}

declare module 'htmltojsx/src/htmltojsx-component' {
  declare module.exports: any;
}

declare module 'htmltojsx/src/htmltojsx' {
  declare module.exports: any;
}

declare module 'htmltojsx/src/magic' {
  declare module.exports: any;
}

declare module 'htmltojsx/test/htmltojsx-test' {
  declare module.exports: any;
}

declare module 'htmltojsx/test/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'htmltojsx/gulpfile.js' {
  declare module.exports: $Exports<'htmltojsx/gulpfile'>;
}
declare module 'htmltojsx/src/cli.js' {
  declare module.exports: $Exports<'htmltojsx/src/cli'>;
}
declare module 'htmltojsx/src/htmltojsx-component.js' {
  declare module.exports: $Exports<'htmltojsx/src/htmltojsx-component'>;
}
declare module 'htmltojsx/src/htmltojsx.js' {
  declare module.exports: $Exports<'htmltojsx/src/htmltojsx'>;
}
declare module 'htmltojsx/src/magic.js' {
  declare module.exports: $Exports<'htmltojsx/src/magic'>;
}
declare module 'htmltojsx/test/htmltojsx-test.js' {
  declare module.exports: $Exports<'htmltojsx/test/htmltojsx-test'>;
}
declare module 'htmltojsx/test/test-helpers.js' {
  declare module.exports: $Exports<'htmltojsx/test/test-helpers'>;
}
