// flow-typed signature: 7a39295e44dfbc913bbea506ba1d6c11
// flow-typed version: <<STUB>>/postcss-apply_v^0.8.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-apply'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-apply' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-apply/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-apply/dist/utils/index' {
  declare module.exports: any;
}

declare module 'postcss-apply/dist/visitor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-apply/dist/index.js' {
  declare module.exports: $Exports<'postcss-apply/dist/index'>;
}
declare module 'postcss-apply/dist/utils/index.js' {
  declare module.exports: $Exports<'postcss-apply/dist/utils/index'>;
}
declare module 'postcss-apply/dist/visitor.js' {
  declare module.exports: $Exports<'postcss-apply/dist/visitor'>;
}
declare module 'postcss-apply/index' {
  declare module.exports: $Exports<'postcss-apply'>;
}
declare module 'postcss-apply/index.js' {
  declare module.exports: $Exports<'postcss-apply'>;
}
