// flow-typed signature: d2b0bcf26c02557e9c6aabbe051f43da
// flow-typed version: <<STUB>>/sass-mq_v^3.3.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-mq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-mq' {
  declare module.exports: any;
}
