// flow-typed signature: c63e29cab2ce774bd658cda7818d3c33
// flow-typed version: <<STUB>>/styletron-preact_v^2.5.7/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-preact/lib/index' {
  declare module.exports: any;
}

declare module 'styletron-preact/lib/provider' {
  declare module.exports: any;
}

declare module 'styletron-preact/lib/styled' {
  declare module.exports: any;
}

declare module 'styletron-preact/lib/test/browser' {
  declare module.exports: any;
}

declare module 'styletron-preact/src/index' {
  declare module.exports: any;
}

declare module 'styletron-preact/src/provider' {
  declare module.exports: any;
}

declare module 'styletron-preact/src/styled' {
  declare module.exports: any;
}

declare module 'styletron-preact/src/test/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-preact/lib/index.js' {
  declare module.exports: $Exports<'styletron-preact/lib/index'>;
}
declare module 'styletron-preact/lib/provider.js' {
  declare module.exports: $Exports<'styletron-preact/lib/provider'>;
}
declare module 'styletron-preact/lib/styled.js' {
  declare module.exports: $Exports<'styletron-preact/lib/styled'>;
}
declare module 'styletron-preact/lib/test/browser.js' {
  declare module.exports: $Exports<'styletron-preact/lib/test/browser'>;
}
declare module 'styletron-preact/src/index.js' {
  declare module.exports: $Exports<'styletron-preact/src/index'>;
}
declare module 'styletron-preact/src/provider.js' {
  declare module.exports: $Exports<'styletron-preact/src/provider'>;
}
declare module 'styletron-preact/src/styled.js' {
  declare module.exports: $Exports<'styletron-preact/src/styled'>;
}
declare module 'styletron-preact/src/test/browser.js' {
  declare module.exports: $Exports<'styletron-preact/src/test/browser'>;
}
