// flow-typed signature: 0374f0ce2939587a8b38c23daf625cf2
// flow-typed version: <<STUB>>/styletron_v^2.5.7/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron/lib/client' {
  declare module.exports: any;
}

declare module 'styletron/lib/server' {
  declare module.exports: any;
}

declare module 'styletron/src/client' {
  declare module.exports: any;
}

declare module 'styletron/src/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron/lib/client.js' {
  declare module.exports: $Exports<'styletron/lib/client'>;
}
declare module 'styletron/lib/server.js' {
  declare module.exports: $Exports<'styletron/lib/server'>;
}
declare module 'styletron/src/client.js' {
  declare module.exports: $Exports<'styletron/src/client'>;
}
declare module 'styletron/src/server.js' {
  declare module.exports: $Exports<'styletron/src/server'>;
}
