// flow-typed signature: b7015f76725c8c2d9a55354dea43f393
// flow-typed version: <<STUB>>/styletron-server_v^2.5.7/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-server/lib/base-obj-to-css' {
  declare module.exports: any;
}

declare module 'styletron-server/lib/cache-to-css' {
  declare module.exports: any;
}

declare module 'styletron-server/lib/cache-to-stylesheets-old-ie' {
  declare module.exports: any;
}

declare module 'styletron-server/lib/cache-to-stylesheets' {
  declare module.exports: any;
}

declare module 'styletron-server/lib/generate-html-string' {
  declare module.exports: any;
}

declare module 'styletron-server/lib/styletron-server' {
  declare module.exports: any;
}

declare module 'styletron-server/lib/test/index' {
  declare module.exports: any;
}

declare module 'styletron-server/src/base-obj-to-css' {
  declare module.exports: any;
}

declare module 'styletron-server/src/cache-to-css' {
  declare module.exports: any;
}

declare module 'styletron-server/src/cache-to-stylesheets-old-ie' {
  declare module.exports: any;
}

declare module 'styletron-server/src/cache-to-stylesheets' {
  declare module.exports: any;
}

declare module 'styletron-server/src/generate-html-string' {
  declare module.exports: any;
}

declare module 'styletron-server/src/styletron-server' {
  declare module.exports: any;
}

declare module 'styletron-server/src/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-server/lib/base-obj-to-css.js' {
  declare module.exports: $Exports<'styletron-server/lib/base-obj-to-css'>;
}
declare module 'styletron-server/lib/cache-to-css.js' {
  declare module.exports: $Exports<'styletron-server/lib/cache-to-css'>;
}
declare module 'styletron-server/lib/cache-to-stylesheets-old-ie.js' {
  declare module.exports: $Exports<'styletron-server/lib/cache-to-stylesheets-old-ie'>;
}
declare module 'styletron-server/lib/cache-to-stylesheets.js' {
  declare module.exports: $Exports<'styletron-server/lib/cache-to-stylesheets'>;
}
declare module 'styletron-server/lib/generate-html-string.js' {
  declare module.exports: $Exports<'styletron-server/lib/generate-html-string'>;
}
declare module 'styletron-server/lib/styletron-server.js' {
  declare module.exports: $Exports<'styletron-server/lib/styletron-server'>;
}
declare module 'styletron-server/lib/test/index.js' {
  declare module.exports: $Exports<'styletron-server/lib/test/index'>;
}
declare module 'styletron-server/src/base-obj-to-css.js' {
  declare module.exports: $Exports<'styletron-server/src/base-obj-to-css'>;
}
declare module 'styletron-server/src/cache-to-css.js' {
  declare module.exports: $Exports<'styletron-server/src/cache-to-css'>;
}
declare module 'styletron-server/src/cache-to-stylesheets-old-ie.js' {
  declare module.exports: $Exports<'styletron-server/src/cache-to-stylesheets-old-ie'>;
}
declare module 'styletron-server/src/cache-to-stylesheets.js' {
  declare module.exports: $Exports<'styletron-server/src/cache-to-stylesheets'>;
}
declare module 'styletron-server/src/generate-html-string.js' {
  declare module.exports: $Exports<'styletron-server/src/generate-html-string'>;
}
declare module 'styletron-server/src/styletron-server.js' {
  declare module.exports: $Exports<'styletron-server/src/styletron-server'>;
}
declare module 'styletron-server/src/test/index.js' {
  declare module.exports: $Exports<'styletron-server/src/test/index'>;
}
