name: CORE4 label enforcement
permissions:
  contents: read
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened, edited]
jobs:
  require-label:
    uses: guardian/.github/.github/workflows/require-label.yaml@3522b599ee9e7d77089f505fed04f084c8b5fac2 #  v3.1.2
