name: Commercial E2E Tests
on:
    pull_request:
        paths:
            - static/src/javascripts/projects/common/modules/commercial/**
            - static/src/javascripts/projects/commercial/**
            - static/src/javascripts/projects/common/modules/spacefinder-*
            - commercial/**
            - cypress/**
            - cypress.config.ts
            - .github/workflows/commercial-e2e.yml

concurrency:
    group: 'commercial-e2e-${{ github.head_ref }}'
    cancel-in-progress: true

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            # Frontend
            - name: Checkout frontend
              uses: actions/checkout@v3
              with:
                  path: ./frontend

            - name: Setup frontend node
              uses: actions/setup-node@v3
              with:
                  node-version-file: './frontend/.nvmrc'

            - name: Install Frontend dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./frontend

            # DCR
            - name: Checkout DCR
              uses: actions/checkout@v3
              with:
                  repository: guardian/dotcom-rendering
                  path: ./dcr

            - name: Setup DCR node
              uses: actions/setup-node@v3
              with:
                  node-version-file: './dcr/.nvmrc'

            - name: Install DCR dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./dcr

            - name: Build DCR
              run: make build
              working-directory: ./dcr/dotcom-rendering

            - name: Run Cypress
              uses: cypress-io/github-action@v4
              with:
                  install: false
                  start: make -C ../dcr/dotcom-rendering start-ci, make commercial-dev
                  working-directory: frontend
                  wait-on: 'http://localhost:3030, http://localhost:3031/graun.standalone.commercial.js'
                  wait-on-timeout: 30
                  browser: chrome
                  spec: cypress/e2e/**/*
              env:
                  PORT: 3030
                  COMMERCIAL_BUNDLE_URL: http://localhost:3031/graun.standalone.commercial.js

            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: cypress-videos
                  path: frontend/cypress/videos

            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: frontend/cypress/screenshots
