name: Commercial E2E Tests
on:
    [push]
    # will change to below when we have a stable branch
    #
    # pull_request:
    #     paths:
    #         - static/src/javascripts/projects/common/modules/commercial
    #         - static/src/javascripts/projects/commercial
    #         - commercial

concurrency:
    group: 'commercial-e2e'
    cancel-in-progress: true

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout frontend
              uses: actions/checkout@v3
              with:
                  path: ./frontend

            - name: Checkout DCR
              uses: actions/checkout@v3
              with:
                  repository: guardian/dotcom-rendering
                  path: ./dcr

            - name: Setup node
              uses: guardian/actions-setup-node@main
              with:
                  node-version: '14.18.3'

            - name: Install frontend dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./frontend

            - name: Install DCR dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./dcr

            - name: Build Frontend JS
              run: make compile-javascript-dev
              working-directory: ./frontend

            - name: Build DCR
              run: make build
              working-directory: ./dcr/dotcom-rendering

            - name: Run Cypress
              uses: cypress-io/github-action@v4
              with:
                  install: false
                  start: make -C ../dcr/dotcom-rendering start-ci, npx -http-server -p 3000 static/target
                  working-directory: frontend
                  wait-on: 'http://localhost:3030, http://localhost:3000/javascripts/commercial/graun.standalone.commercial.js'
                  wait-on-timeout: 30
                  browser: chrome
                  spec: cypress/e2e/**/*
              env:
                  PORT: 3030
                  COMMERCIAL_BUNDLE_URL: http://localhost:3000/javascripts/commercial/graun.standalone.commercial.js
