name: Update Dependency Graph for sbt
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@9f265659d3bb64ab1440b03b12f4d47a24320917 # v6
      - name: Install sbt
        uses: guardian/setup-scala@f8b37d4380d93ee5c37739fd8aea97f7c580034a # v1.1.0
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@d892df7c6b92ce2a2ac44815f573e9e126de3670 # v3.2.1
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write
