name: Update Dependency Graph for sbt
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@v6
      - name: Install sbt
        uses: guardian/setup-scala@v1
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@v3
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write
