name: Update security.txt Expires Field

on:
  schedule:
    - cron: '0 8 30 4 *' # Runs at 8:00 UTC Q:on April 30th every year
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-expires:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Expires field in security.txt
        run: python3 security-txt.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-security-txt-${{ github.run_number }}
          git add facia/public/security.txt
          git commit -m "Update Expires field in security.txt to next year (automated)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}